### ISSUE TITLE
Invalid ref call attempt: 5127 - 7983 - 88

### ISSUE THREAD

**Issue by MrWhitee4** [esx-framework/es_extended#1000]
If I disconnect from a server and rejoin I get those errors and I have to quit the game in order to be able to join a server.

https://i.imgur.com/qJOEZTG.png

Invalid ref call attempt: 5127
Invalid ref call attempt: 7938
Invalid ref call attempt: 88

I researched in the FiveM Forum but I haven't seen a solution to it.

**Comment by ArkSeyonet** [comment]
This is too vague, and there is not enough information to have a clue what the problem would be.
