### ISSUE TITLE
[Feature Request] More Genders in Identity

### ISSUE THREAD

**Issue by rrphacker** [esx-framework/es_extended#1012]
Add more genders to the identity module, for example: transgender, cisgender, other...

**Comment by Dislaik** [comment]
I think that is unnecessary for a default version

**Comment by ArkSeyonet** [comment]
No. The server owner can add this.

**Comment by rrphacker** [comment]
In the database says 'isMale', so the values are true or false.
Can you add a easier support like using 'gender' in the database so we can use the common 'M' and 'F', and add new ones ourself?

**Comment by rrphacker** [comment]
> No. The server owner can add this.
In the database says 'isMale', so the values are true or false.
Can you add a easier support like using 'gender' in the database so we can use the common 'M' and 'F', and add new ones ourself?

**Comment by rrphacker** [comment]
> No. The server owner can add this.

In the database says 'isMale', so the values are true or false.
Can you add a easier support like using 'gender' in the database so we can use the common 'M' and 'F', and add new ones ourself?

**Comment by SwAtRaNgEr** [comment]
There's only two genders.

**Comment by Quinten-Gelderland** [comment]
> > No. The server owner can add this.
> 
> In the database says 'isMale', so the values are true or false.
> Can you add a easier support like using 'gender' in the database so we can use the common 'M' and 'F', and add new ones ourself?



BRUH stfu there are only 2 genders

**Comment by ArkSeyonet** [comment]
Relax guys, your personal beliefs on the subject shouldn't affect people's ability to roleplay whatever they want to. Regardless of whether it's factual information or not.
