### ISSUE TITLE
Problem with npm

### ISSUE THREAD

**Issue by OnyxException** [esx-framework/es_extended#1024]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ x] I'm using the latest version (develop branch).
- [ x] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [ x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> That es_extened working after npm init

## Current Result

**I run npm init and then after that npm i and i get his error:  npm WARN es_extended@1.0.0 No repository field.**

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. **Install es_extended**
2. **run npm init**
3. **run npm i**

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (es_extended)
version: (1.0.0)
git repository:
keywords:
author:
license: (ISC)
About to write to /srv/[.xeveliaSystem]/[.fiveM]/[.latnd]/Entwicklungsserver/server-data/resources/[.esx]/es_extended/package.json:

{
  "name": "es_extended",
  "version": "1.0.0",
  "description": "### Sill looking for old version ? => https://github.com/ESX-Org/es_extended/tree/v1-final",
  "main": "index.js",
  "directories": {
    "doc": "docs"
  },
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

Is this ok? (yes)
root@ssh:/srv/[.xeveliaSystem]/[.fiveM]/[.latnd]/Entwicklungsserver/server-data/resources/[.esx]/es_extended# npm i
npm WARN es_extended@1.0.0 No repository field.
`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`No`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

`No`

**Comment by izio38** [comment]
According to the readme you shouldn't do a `npm init` first.

Then, did you ran `npm i` into the es_extended folder ?

Also, I see no error but a warning due to the `npm init` I guess.
