### ISSUE TITLE
Didn't loading my spawn 

### ISSUE THREAD

**Issue by supersaiyan94** [esx-framework/es_extended#1046]

**Comment by supersaiyan94** [comment]
Hellow i am using the v1 final of es extended but when i leave the server my possion and load out not saved can someone help?

**Comment by trkyshorty** [comment]
any error log on console?

**Comment by supersaiyan94** [comment]
nothing on console or f8

**Comment by supersaiyan94** [comment]
in 1.2.0 version working fine
