### ISSUE TITLE
DATABASE IS EMPTY

### ISSUE THREAD

**Issue by HsiReyak** [esx-framework/es_extended#1051]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [ ] The issue has occured more than once.
- [ ] I have followed the readme and my setup is correct.
- [ ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Errors

>es_extended.sql = "CREATE DATABASE IF NOT EXISTS `es_extended`;"

THIS WILL JUST CREATE A EMPTY DATABASE

**Comment by paulanerpanther** [comment]
It will create the database automaticly
