### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by NathanWhite14** [esx-framework/es_extended#1054]
## Issue Checklist

- [ ] I'm using the latest version (develop branch).
- [ ] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [ x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x ] I'm certain this is an issue with es_extended and not my personal module / script.

Issue - https://gyazo.com/ff33e109d19fc84f5e5189411138a75d
SCRIPT ERROR: @es_extended/client/functions.lua:232: attempt to index a nil value (field '?')

**Comment by XvenDeR** [comment]
Another non sense issue...

**Comment by NathanWhite14** [comment]
If it was a non sense issue i wouldnt of posted it, please explain to me how it is a non sense issue...

**Comment by XvenDeR** [comment]
First I think your using old version. Second I think identity is integrated as module. Third you should realize at this point.

**Comment by izio38** [comment]
This should be closed.
