### ISSUE TITLE
Loadout doesn't saving in es_extended final

### ISSUE THREAD

**Issue by slenderman020** [esx-framework/es_extended#1056]
HELP !
The loadout of my character is saved in the database column 'loadout' but when the character is loaded the weapons wont load, even more strange is that if I use the command /clearloadout the command will eliminate weapons that are in the database column 'loadout' but my character dont have.
Im using es_extended v1.2 Final and before asking the column 'inventory' of the users table is empty ( [] )
I check the code but y couldn't find any errors. 
Please help

**Comment by izio38** [comment]
You didn't use the issue template. This should be closed.

Thanks.
