### ISSUE TITLE
First spawnpoint. How to change it?

### ISSUE THREAD

**Issue by CyberBismo** [esx-framework/es_extended#1067]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ X ] I'm using the latest version (develop branch).
- [ X ] The issue has occured more than once.
- [ X ] I have followed the readme and my setup is correct.
- [ X ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ X ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

**There should be a XYZ location option in the config file that will give you the opportunity to modify the spawnpoint of new user connections.**

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

**After hours, yes hours of troubleshooting, I found out that the es_extended resource is changing the "fivem-map-hipster/skater" location script. And overwrites these changes.

I've deleted my user database to debug this and verify everytime I restarted my server to check what resource caused this problem to occur.**

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

**There's really nothing to do other than installing the es_extended and see the spawnpoint get set to job center (even without any esx_jobs installed)**

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`no error, just a simple fix is needed`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`nothing I know of`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

`solution would be as mentioned previously. Add a config option to change spawnpoint using XYZ location`

**Comment by izio38** [comment]
Hi @CyberBismo,

Just to be sure, do we talk about Esx v2 ?

**Comment by CyberBismo** [comment]
> Hi @CyberBismo,
> 
> Just to be sure, do we talk about Esx v2 ?

Hi, I have had problems with the latest version. "Loading" never ending. So I'm not sure what version I am using. BUT, I just figured where the location script was. So I fixed the problem 👍

**Comment by izio38** [comment]
Could you be more specific, please ?
Does the comment you added is related to the inital issue ?

**Comment by CyberBismo** [comment]
> Could you be more specific, please ?
> Does the comment you added is related to the inital issue ?

Yes, the problem is fixed, but I think there should be an easier option for this.

**Comment by izio38** [comment]
![image](https://user-images.githubusercontent.com/9900846/104830031-95f44480-587a-11eb-913c-58d5761e9598.png)

Easier than editing a config file ?

**Comment by CyberBismo** [comment]
> ![image](https://user-images.githubusercontent.com/9900846/104830031-95f44480-587a-11eb-913c-58d5761e9598.png)
> 
> Easier than editing a config file ?

Whatever files you've got there, is not what I've got here. 
![image](https://user-images.githubusercontent.com/67421508/104853922-5114f000-5904-11eb-9d4c-d7be1ca9c34a.png)

**Comment by CyberBismo** [comment]
So, it's still not fixed, the spawn location is at the Job center... How can this be fixed?

**Comment by mosheba1** [comment]
Having the same issue. It's really annoying tho

**Comment by mosheba1** [comment]
I found it

**Comment by mosheba1** [comment]
The way to change is to go to es_extended/server/main.lua line 205

**Comment by CyberBismo** [comment]
> The way to change is to go to es_extended/server/main.lua line 205

Found that too, and it worked for a day, now it's back to Job center. As if there's somewhere else overwriting.

Line 205 looks like: userData.coords = {x = -1037.63, y = -2737.58, z = 20.17, heading = 329.1}
And this is NOT the job center coordinates.

**Comment by ArkSeyonet** [comment]
This is ESX1, and not supported here anymore.

**Comment by CyberBismo** [comment]
> This is ESX1, and not supported here anymore.

Can you give me a download link for the latest ESX please.

**Comment by XvenDeR** [comment]
> > This is ESX1, and not supported here anymore.
> 
> Can you give me a download link for the latest ESX please.

Hello, wth? You are in it right now.
