### ISSUE TITLE
Spawn at job center

### ISSUE THREAD

**Issue by mosheba1** [esx-framework/es_extended#1071]
Hey guys,

i have this issue where new players keep spawning at the job center location knowing that i edited the map resource where they should spawn but it still spawns them in the job center. any fix?

**Comment by XvenDeR** [comment]
Edit in users table - position section.

**Comment by mosheba1** [comment]
@XvenDeR but what does it have to do with new players who is first spawning?

**Comment by ArkSeyonet** [comment]
Is this for ESX1 or ESX2?

**Comment by mosheba1** [comment]
ESX 1.2

**Comment by ArkSeyonet** [comment]
ESX 1.2 is not supported anymore. es_extended on the github is now ESX2 only.
