### ISSUE TITLE
Attemp to call a nil value (field ‘ShowInventory’)

### ISSUE THREAD

**Issue by juanpimr2** [esx-framework/es_extended#1075]
I just installed ESX 2 into my new server, im Really new at lua and i dont really know what i should do with some resources or how to start coding

I wan to work in the inventory system based on es_extended, but, it doesnt work.

I press the Inventory Key informed in the cofig file \server-data\resources\es_extended\config\default\config.lua

“Config.InventoryKey = “REPLAY_START_STOP_RECORDING_SECONDARY” – Key F2 by default”

<img width="736" alt="code" src="https://user-images.githubusercontent.com/48697457/105478223-36939b80-5ca3-11eb-8b2d-7f4cce47661e.PNG">

I literally change a little bit the code to directly execute the ShowInventory() Function but i got this error

![20210121234025_1](https://user-images.githubusercontent.com/48697457/105478247-3f846d00-5ca3-11eb-8146-de171b773ebd.jpg)

Im new at lua i know i can doing a biiig mistake that is cleary visible but for me is not =( I greatly appreciate your help!

**Comment by DataIndev** [comment]
Hi dude DP_Inventory only work with es_extended 1.2: https://github.com/esx-framework/es_extended/tree/v1-final

**Comment by juanpimr2** [comment]
No, I dont even know what DP_Inventory is, im trying with the native files of es_extended2-develop (most recent) and it supose to open the inventory when i press F2 but nothing happen

**Comment by TasoOneAsia** [comment]
ESX v2 is currently in the **development** phase, meaning certain aspects of it, such as the inventory are not yet complete. We do not recommend you use the v2 unless you are a developer looking to get used to its functionality prior to release.

Please use ESX v1-Final as it is considered the most stable prior release.
