### ISSUE TITLE
[ERROR]Mysql DataBase

### ISSUE THREAD

**Issue by Alivionx** [esx-framework/es_extended#1076]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x ] I'm using the latest version (develop branch).
- [ x] The issue has occured more than once.
- [x ] I have followed the readme and my setup is correct.
- [x ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

**That the connection to my mysql database is succesfull**

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

**The server is trying to connect to my mysql database but he can't for some reason, this is the string i use to connect to my data base
`set mysql_connection_string "mysql://u1_RlMo2S6q9z:RV.eB4amDyEk^gu8mfN@!AgU@localhost:3306/s1_es_extended?charset=utf8mb4"**`
I tryed everything i change localhost to 127.0.0.1 and i tryed my public ip. i even tryed my docker image ip addres but no luck.
![image](https://user-images.githubusercontent.com/39876601/105576558-d91b4f80-5d73-11eb-9621-5765a58a0183.png)
![image](https://user-images.githubusercontent.com/39876601/105576559-de789a00-5d73-11eb-9e16-119ebf727315.png)
![image](https://user-images.githubusercontent.com/39876601/105576573-f4865a80-5d73-11eb-8e70-37493bf39dc7.png)
But i can see the data base in phpmyadmin with the same user

**Comment by Mycroft-Studios** [comment]
use mariaDB
