### ISSUE TITLE
ES_EXTENDED Inventory

### ISSUE THREAD

**Issue by SeptJack** [esx-framework/es_extended#1077]
## Issue Checklist

- [ ] I'm using the latest version (develop branch).
- [ ] The issue has occured more than once.
- [ ] I have followed the readme and my setup is correct.
- [ ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

**Pressing F2 opens inventory**

## Current Result

**Pressing F2 doesn't open inventory without any errors**

**Comment by Mycroft-Studios** [comment]
There is no inventory currently

**Comment by SeptJack** [comment]
> There is no inventory currently

Oh ok thank you
