### ISSUE TITLE
Included modules

### ISSUE THREAD

**Issue by CyberBismo** [esx-framework/es_extended#1078]
The image attached is what happends after I try to use /skin in chat.

I have tried both removing the esx_skin and still same issue.

I'm running the latest version of ESX (2).

![image](https://user-images.githubusercontent.com/67421508/106199555-e68e6a80-61b5-11eb-9498-1505ca727b7b.png)

**Comment by XvenDeR** [comment]
Are you running develop branch or main?

**Comment by CyberBismo** [comment]
master

**Comment by CyberBismo** [comment]
for now, I went back to the previous version ESX 1.#, this is working xD
