### ISSUE TITLE
Invalid ref call attempt

### ISSUE THREAD

**Issue by andreaconfa** [esx-framework/es_extended#1080]
Hi, when joining server i get tons of "Invalid ref call attempt" spammed in all my client console.... how i can fix it?

attacched the log of the client
[CitizenFX_log_2021-01-30T121029 (1).log](https://github.com/esx-framework/es_extended/files/5914064/CitizenFX_log_2021-01-30T121029.1.log)

**Comment by Akkiru** [comment]
bump, same problem

**Comment by ESXCrackhead** [comment]
Not possible to identify this issue with the provided information. Please do more research and provide more information, otherwise there isn't anything that we can possibly do.
