### ISSUE TITLE
It doesnt save ammo clips to loadout DB

### ISSUE THREAD

**Issue by giannis97** [esx-framework/es_extended#1084]
## Bug Report

It doesnt save ammo clips to loadout DB

**Comment by SimpleOgi** [comment]
Did you find a fix for this?

**Comment by DanyCryEn** [comment]
Did you find fix?

**Comment by Mycroft-Studios** [comment]
That is purposeful, you wouldn't store that data in a database

**Comment by giannis97** [comment]
any way to store ammo clips into DB?

**Comment by Mycroft-Studios** [comment]
No, you would be lagged massively, there is also no possible way to do so without creating an entire ammo system

**Comment by giannis97** [comment]
you dont know what you saying , because i have seen a lot of servers doing it.
so?

**Comment by Mycroft-Studios** [comment]
Then they Probably have a 3rd party script that does so

**Comment by Mycroft-Studios** [comment]
and considering I'm a team member, yes I know exactly what I'm saying

**Comment by giannis97** [comment]
ok so you know a way to do it
to store ammo in db

**Comment by Mycroft-Studios** [comment]
I've never seen it actually save the ammo clips so, it shows it saves ammo itself but not the actual clips, it just adds ammo

**Comment by ESXCrackhead** [comment]
If you want to see it, make a suggestion on the Discord, and maybe someone will code it. This is not an issue, and it doesn't belong on the Github.
