### ISSUE TITLE
Change maxweight

### ISSUE THREAD

**Issue by KingRyuShin** [esx-framework/es_extended#1085]
How could we change the maxweight value while ingame..

Lets say I want to give player more inventory space if they have a bag.. but it doesn't work..

> Citizen.CreateThread(function()
> 	while true do
> 		ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin, jobSkin)
> 			if skin.bags_1 ~= 45 then
> 				TriggerServerEvent('esx:setMaxWeight', 24)
> 			else
> 				TriggerServerEvent('esx:setMaxWeight', 100)
> 			end
> 		end)
> 		Wait(10)
> 	end
> end)

**Comment by ESXCrackhead** [comment]
ESX1 Code is not supported on the Github anymore.
