### ISSUE TITLE
positions are saved randomly

### ISSUE THREAD

**Issue by Jujugin** [esx-framework/es_extended#1087]
Hello ,
I have a problem since using the old version of es_extended without needing essentialmode

Player positions are saved in the database but sometimes when they log in they go back to the starting spawn point

There is no error in the console

I use onesync, maybe I have to adapt it but I couldn't find where to do it

Thank you for answering me, bye

**Comment by ExeDesK** [comment]
Are you using a Linux OS ?

**Comment by Mycroft-Studios** [comment]
To fix, remove all code from spawn manager and map manager, keeping the FX manifest the same

**Comment by ESXCrackhead** [comment]
Old ESX code is not supported anymore. You'll find no support for it here.
