### ISSUE TITLE
function module.IsModuleInGroup in es_extended/boot/shared/module.lua looks like it returns a bad result

### ISSUE THREAD

**Issue by emtneutrino** [esx-framework/es_extended#1088]
## Bug Report

> module.IsModuleInGroup function in es_extended/boot/shared/module.lua seems to return a bad result.  It does not actually check if the module is in the group, only that it is not nil.  It currently doesn't seem to be used anywhere.

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ X] I'm using the latest version (develop branch).
- [ ] The issue has occured more than once.
- [X ] I have followed the readme and my setup is correct.
- [X ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [X ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> It should return whether or not a module is in the specified group

**_Example text_**

## Current Result

> It currently is 'return module.Entries[name] ~= nil'.  This only returns whether or not the module has a group.

**_Example Text_**

## How to reproduce the problem

> Was randomly looking at code and thought it looked incorrect

1. **_Example List_**
2. **_Example List_**
3. **_Example List_**

## Errors

> It doesn't seem to be used anywhere, but seems like it would return true if the module is in a group, but not neccesarily the group specified in the paramaters.

`example code block for error`

### Code Block referenced by the error

> It doesn't seem to be used anywhere

`example code block for error context`

### Possible Solution

> change code to `return (module.Entries[name] ~= nil) and (module.Entries[name] == group)`

**Comment by ESXCrackhead** [comment]
Please make the changes that you would like, and submit a PR so that we can get this updated. I am not currently able to do any coding right now, as I have a lot of personal things going on in RL, and most of the other developers are busy on certain module projects.
