### ISSUE TITLE
Inventory: Weight+Limit systems working together

### ISSUE THREAD

**Issue by rrphacker** [esx-framework/es_extended#1089]
## Feature Request for ESX2

**Is your feature request related to a problem? Please describe.**
Back in the days, esx used a limit to how many items can be carried in the inventory.
Then it was switched to weight instead, and some server had problems like: _"How to put a limit in how many medkits can people/paramedics have"_.
This lead to not easy solutions, because too much weight means few other items and too little means that you could have many medkits on the go.

**Describe the solution you'd like**
Both systems have their pros and cons, so I hope that both systems could be implemented.
Then the server owners could choose which one do we want to activate and in which items, giving so much flexibility than before.
Now that ESX2 is on the go and the Inventory module is in creation I think it could be easier to implement as well. _Better sooner than later right? hehe_

**Describe alternatives you've considered**
This could also be extended in the future to affect the trunk of the car or player properties.
Even with customizable settings to have different limits _(but the same weight)_ if you store it in the trunk or your house

**Teachability, Documentation, Adoption, Migration Strategy**
Maybe it could be as simple as something like this:

> 1. limit = -1 >>> limit system not used in this item
> 2. limit = 0 >>> you can not have this item in your inventory (because maybe is spawneable by admins only)
> 3. weight = -1.0 >>> weight system not used in this item
> 4. weight = 0.0 >>> you can have infinite quantity of this item in your inventory
> 5. weight = N.N >>> the actual weight of the item, in grams
> 
> CreateItem("Medkit", 5, -1)
> CreateItem("Hamburger", -1, 0.2)
> CreateItem("WeaponName", 4, 3.0)
> 
> Or save it in a database like always

Easy to understand in the docs as well.

Thank you for reading and have a great 2021 if possible

**Comment by XvenDeR** [comment]
This is great. 💯

**Comment by Tinky124** [comment]
This is great. 💯

**Comment by Mycroft-Studios** [comment]
This is most likely to be the system we use 👍
