### ISSUE TITLE
ESX 2:modules\__core__\skin\client\module.lua: line 59: module.Humans assignment looks wrong

### ISSUE THREAD

**Issue by emtneutrino** [esx-framework/es_extended#1091]
Bug Report
It seems like module.Humans table will have an extra MP_F_FREEMODE_01 entry.  Skin changer only lets you select first 45 models in `modules\__core__\skin\data\index.html`  line 61:`<input type="range" min="0" max="45" value="0" step="1" class="slider" data-type="model" id="changeModel" oninput="modelOutput.value=value">`

Issue Checklist
[X] I'm using the latest version (develop branch).
[  ] The issue has occured more than once.
[X] I have followed the readme and my setup is correct.
[X] I have searched the ESX forum and Github issues for solution before submitting my issue.
[X] I'm certain this is an issue with es_extended and not my personal module / script.

Expected Result
module.Humans table contains unique human models

Current Result
module.Humans has an extra MP_F_FREEMODE_01 entry

How to reproduce the problem
Code at line 59 seems incorrect

Errors
No recognizeable errors

Code Block referenced by the error
`module.Humans  = table.concat({MP_M_FREEMODE_01, MP_F_FREEMODE_01}, table.filter(PED_MODELS_HUMANS, function(x) return (x ~= MP_M_FREEMODE_01) and (t ~= MP_F_FREEMODE_01) end))`

Possible Solution
Change `(t ~= MP_F_FREEMODE_01)` to `(x ~= MP_F_FREEMODE_01)`
`(t ~= MP_F_FREEMODE_01)` will always be true as far as I can tell
It will not filter out MP_F_FREEMODE_01 from the table and add it again
Corrected line:
`module.Humans  = table.concat({MP_M_FREEMODE_01, MP_F_FREEMODE_01}, table.filter(PED_MODELS_HUMANS, function(x) return (x ~= MP_M_FREEMODE_01) and (x ~= MP_F_FREEMODE_01) end))`

**Comment by ESXCrackhead** [comment]
Please make the changes, and make a pull request so that we can get this updated.
