### ISSUE TITLE
ESX 2:nitpicking code in modules\__base__\vehicleshop\client\module.lua

### ISSUE THREAD

**Issue by emtneutrino** [esx-framework/es_extended#1092]
# Bug Report
-module.windowSizY should probably be renamed module.windowSizeY
-module.currentDisplayVehicle is initialized twice
-module.selectedCategory initialization not necessary - is it just to follow initialization convention?

# Issue Checklist
- [X] I'm using the latest version (develop branch).
- [X] The issue has occured more than once.
- [X] I have followed the readme and my setup is correct.
- [X] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [X] I'm certain this is an issue with es_extended and not my personal module / script.

# Expected Result
-module.windowSizY should be renamed module.windowSizeY to follow same naming convention as module.windowSizeX
-module.currentDisplayVehicle should be initialized only once
-module.selectedCategory doesn't need initialization

# Current Result
-module.windowSizY doesn't follow naming convention
-module.currentDisplayVehicle initialized twice
-module.selectedCategory initialized to itself or nil

# How to reproduce the problem
N/A

# Errors
N/A

# Code Block referenced by the error
line 37:`module.windowSizY                     = 0.15`
line 872:`            module.RenderBox(module.xoffset - 0.05, module.windowSizeX, (module.yoffset - 0.0325), module.windowSizY, 0, 0, 0, 225)`

line 43:`module.currentDisplayVehicle          = nil`
line 47:`module.currentDisplayVehicle          = nil`

line 66:`module.selectedCategory               = module.selectedCategory or nil`

# Possible Solution
-Change module.windowSizY to module.windowSizeY
-Remove duplicate initialization of module.currentDisplayVehicle
-Remove module.selectedCategory initialization or remove `or nil` to kind of follow initialization convention

**Comment by ESXCrackhead** [comment]
vehicleshop is being redone, so expect this entire module to be coded differently.
