### ISSUE TITLE
ESX 2: nitpicking code in various places

### ISSUE THREAD

**Issue by emtneutrino** [esx-framework/es_extended#1094]
# Bug Report
-`locales\en.lua` line 65:`account_commandderror_account` should be renamed `account_commanderror_account`(extra d in command)
-update `modules\__core__\account\server\main.lua` line 27 and line 47: use `account_commanderror_account`

-`modules\__core__\db\server\events.lua` line 28 and line 58:rename `ADD_COLUMN_IN_NOT_EXISTS_PROCEDURE` to `ADD_COLUMN_IF_NOT_EXISTS_PROCEDURE`

-`modules\__core__\account\client\module.lua` line 38: `Accounts` is unused in its scope

# Issue Checklist
- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

# Expected Result
-`account_commanderror_account` named consistently like `account_commanderror_money`
-`ADD_COLUMN_IF_NOT_EXISTS_PROCEDURE` named like the command it is set to
-declaration of `Accounts` is unnecessary

# Current Result
-`account_commandderror_account` is not named similar to `account_commanderror_money`
-`ADD_COLUMN_IN_NOT_EXISTS_PROCEDURE` is misnamed
-`Accounts` is declared, but not used

# How to reproduce the problem
N/A

# Errors
N/A

# Code Block referenced by the error
-`locales\en.lua` line 65:`['account_commandderror_account'] = 'account missing',`
-`modules\__core__\account\server\main.lua` line 27:`		  emitClient("chat:addMessage", player.source, {args = {'^1SYSTEM', _U('account_commandderror_account')}})`
-`modules\__core__\account\server\main.lua` line 47:`        emitClient("chat:addMessage", player.source, {args = {'^1SYSTEM', _U('account_commandDerror_account')}})`

-`modules\__core__\db\server\events.lua` line 28:`local ADD_COLUMN_IN_NOT_EXISTS_PROCEDURE = [[`
-`modules\__core__\db\server\events.lua` line 58:`  MySQL.Sync.execute(ADD_COLUMN_IN_NOT_EXISTS_PROCEDURE)`

-`modules\__core__\account\client\module.lua` line 38:`  local Accounts = {}`

# Possible Solution
-Rename `account_commandderror_account` to `account_commanderror_account`
-Rename `ADD_COLUMN_IN_NOT_EXISTS_PROCEDURE` to `ADD_COLUMN_IF_NOT_EXISTS_PROCEDURE`
-Remove `Accounts` declaration

**Comment by ESXCrackhead** [comment]
Make a pull request and contribute that way, please.

ESX2 will only work if everyone contributes because people don't have a lot of free time to make changes, so I would ask you to make a PR for the things that you would like to see changed.
