### ISSUE TITLE
System.NullReferenceException then server crash

### ISSUE THREAD

**Issue by flaxeneel2** [esx-framework/es_extended#1096]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> Server shouldnt crash on `ensure es_extended`

**_Example text_**

## Current Result

> crashes as soon as i `ensure es_extended` the full output is below

`ensure es_extended
Creating script environments for es_extended
[esx] checking manifest
[esx] no changes required in fxmanifest.lua
Started resource es_extended
[esx/core/account] start
[esx/core/events] start
[esx/core/class] start
[esx/core/table] start
[esx/core/string] start
[esx/core/persistent] start
[esx/core/db] start
[esx/core/serializable] start
[esx/core/cache] start
[esx/core/command] start
[esx/core/utils] start
[esx/core/identity] start
[esx/core/async] start
[esx/core/admin] start
[esx/core/camera] start
[esx/core/constants] start
[esx/core/constants] expand PED_BONE_INDEXES enum into global scope
[esx/core/constants] expand PED_COMPONENTS enum into global scope
[esx/core/constants] expand PED_MODEL_NAMES enum into global scope
[esx/core/game.hud] start
[esx/core/input] start
[esx/core/interact] start
[esx/core/inventory] start
[esx/core/math] start
[esx/core/migrate] start
[esx/core/owned.vehicles] start
[esx/core/player] start
[esx/core/role] start
[esx/core/character] start
[esx/core/skin] start
[esx/core/status] start
[esx/core/vehicles] start
[esx/core/connect] start
[esx/core/connect] {"Status":{"StatusMax":100,"EnableStatus":false,"RandomEvents":[{"duration":800,"action":3},{"duration":1500,"action":4},{"duration":1500,"action":5},{"duration":800,"action":6},{"duration":1500,"action":14},{"duration":800,"action":19},{"duration":800,"action":23},{"duration":800,"action":31},{"duration":800,"action":32}],"StatusInfo":{"cocaine":{"iconType":"fontawesome","icon":"fa-caret-up","color":"white","fadeType":"asc"},"drunk":{"iconType":"fontawesome","icon":"fa-glass-martini-alt","color":"purple","fadeType":"asc"},"heroin":{"iconType":"fontawesome","icon":"fa-syringe","color":"brown","fadeType":"asc"},"meth":{"iconType":"fontawesome","icon":"fa-skull-crossbones","color":"yellow","fadeType":"asc"},"hunger":{"iconType":"fontawesome","icon":"fa-hamburger","color":"orange","fadeType":"desc"},"stress":{"iconType":"fontawesome","icon":"fa-brain","color":"pink","fadeType":"asc"},"weed":{"iconType":"fontawesome","icon":"fa-cannabis","color":"green","fadeType":"asc"},"thirst":{"iconType":"fontawesome","icon":"fa-tint","color":"cyan","fadeType":"desc"}},"UseEffects":true,"DefaultValues":[0,0,0,0,0,0,100,100],"UpdateInterval":20,"UseDebugging":false,"NotificationValues":[0,1,2,3,4,5,6,7,8,9,10,15,20,25,50,75,100],"StatusIndex":["stress","drunk","weed","cocaine","heroin","meth","thirst","hunger"],"UseExperimental":false,"TickTime":1000},"Account":{"AccountsIndex":["wallet","fleeca","maze"],"DefaultValues":[0,0,0]},"Cache":{"EnableDebugging":false,"ServerSaveInterval":10,"BasicCachedTables":["vehicles","usedPlates"],"IdentityCachedTables":["owned_vehicles","identities"],"BasicCachedTablesToUpdate":[]},"Admin":{"deleteVehicleRadius":5},"character":{"spawnCoords":{"x":402.86899999994787,"y":-996.596600000048,"z":-99.00030000001425,"heading":180.01846313476563}},"connect":{"notWhitelistedMessage":"You're not whitelisted on this server.","enableWhitelist":false,"enableConnectQueue":true},"identity":{"playerCoordsSaveInterval":10,"isPlayerDeadCheckInterval":0.09999999999999}}
[esx/base/animations] start
[esx/base/clotheshop] start
[esx/base/garages] start
[esx/base/rpchat] start
[esx/base/sit] start
[esx/base/society] start
[esx/base/vehicleshop] start
[esx/base/voice] start
server thread hitch warning: timer interval of 3040 milliseconds
[esx/core/db] ensuring generated schemas
[esx/core/db] table accounts (id, name, owner, money)
[esx/core/db] table bans (id, identifier, reason)
[esx/core/db] table identities (id, identifier, owner, position, first_name, last_name, dob, gender, roles, status, accounts)
[esx/core/db] table inventories (name, owner, items)
[esx/core/db] table migrations (id, module, last)
[esx/core/db] table players (id, identifier, name, identity_id, roles)
[esx/core/db] table whitelists (id, identifier)

Stacktrace:

/proc/self/maps:
408fa000-4090a000 rwxp 00000000 00:00 0 

40bd8000-40cdb000 rwxp 00000000 00:00 0 
41da6000-41e66000 rwxp 00000000 00:00 0 
e6557c0000-e6558c1000 rw-p 00000000 00:00 0 
209c7c40000-209c7c80000 rw-p 00000000 00:00 0 
31604700000-31604740000 rw-p 00000000 00:00 0 
376c65c0000-376c6600000 rw-p 00000000 00:00 0 
409c0e00000-409c0e40000 rw-p 00000000 00:00 0 
42859b40000-42859b80000 ---p 00000000 00:00 0 
4e451a40000-4e451a80000 rw-p 00000000 00:00 0 
532bc4c0000-532bc500000 rw-p 00000000 00:00 0 
5ac4b740000-5ac4b780000 rw-p 00000000 00:00 0 
5e050b80000-5e050bc0000 rw-p 00000000 00:00 0 
62b17f00000-62b17f81000 rw-p 00000000 00:00 0 
65f75540000-65f755d5000 rw-p 00000000 00:00 0 
687d2d80000-687d2dc0000 rw-p 00000000 00:00 0 
68c86300000-68c86340000 rw-p 00000000 00:00 0 
6e608c00000-6e608c2e000 rw-p 00000000 00:00 0 
76cf4d40000-76cf4d80000 rw-p 00000000 00:00 0 
79f577c0000-79f57800000 rw-p 00000000 00:00 0 
8b82d140000-8b82d180000 rw-p 00000000 00:00 0 
8d073100000-8d073140000 rw-p 00000000 00:00 0 
94f08380000-94f083c0000 rw-p 00000000 00:00 0 
97ca12c0000-97ca1300000 rw-p 00000000 00:00 0 
a2ce0400000-a2ce0440000 rw-p 00000000 00:00 0 

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object`

**_Example Text_**

## How to reproduce the problem

> Ran a fiveM server with txAdmin and manually installed all resources (resource list below)

![image](https://user-images.githubusercontent.com/60919292/110005110-90bb5e00-7d31-11eb-9cb0-529eace02754.png)

## Errors

> Sent above

> If the code references a specific line of code within a file, what line is it?

`System.NullReferenceException: Object reference not set to an instance of an object`

### Possible Solution

> Sorry i have no potential solutions

`example code block for solution`

**Comment by flaxeneel2** [comment]
Ok I'm dumb i didnt see the dir on top of the stack trace, so its an issue with directory structure. I am running the server in a ptero panel so the dir is like /home/container/alpine/proc..... but where can i alter these directory values?

**Comment by Mycroft-Studios** [comment]
it is most likely caused by the fact it is a Linux server.

however the team is aware of a chance of a Loop hang that can occur and crash your server.
