### ISSUE TITLE
Does all the esx_* mods work with the new esx

### ISSUE THREAD

**Issue by DreamTexX** [esx-framework/es_extended#1098]
Hey, does all the esx_* mods (esx_skin for example) work with the new esx 2, and if yes how?

**Comment by HumanTree92** [comment]
Quick answer no. But you could have found this out if you searched for it in previous closed issues.

**Comment by DreamTexX** [comment]
Is it forseeable when they will be updated?

**Comment by HumanTree92** [comment]
Just when someone submits a PR and someone on the Team approves it. Currently ESX V2 is what the Team is focusing on as it will be just a 1 resource instead of multiple.

**Comment by Mycroft-Studios** [comment]
No, they will not work together at all and there are no plans for them to ever be able to
