### ISSUE TITLE
Es extended loading screen stack

### ISSUE THREAD

**Issue by kotetsi2** [esx-framework/es_extended#1099]
Hello guys i add es extended in my server everything is okey with me DB but when i try to play in the server my screen stacks after the loading scripts and my player isnt spawn what can i do? I try to change es extended but the same issue can you help me?

**Comment by XiosBombay** [comment]
@kotetsi2 
If using esx v1 final, follow [this](https://github.com/esx-framework/es_extended/issues/1087). 
if using ESX V2, I would change to ESX V1 final unless you know what you're doing.
