### ISSUE TITLE
(global 'ESX') error's

### ISSUE THREAD

**Issue by molcik-dev** [esx-framework/es_extended#1100]
Hi, If I use es_extended version: esx2, I get (global 'ESX') errors of very much resources, and If I use v1 I dont get any problems. I need to use esx2 version, any solution??!
![problem](https://user-images.githubusercontent.com/59299731/112723089-269b7080-8f0d-11eb-82b8-05c841e2ca60.png)

**Comment by molcik-dev** [comment]
And If I use v1 I get this error 
![image](https://user-images.githubusercontent.com/59299731/112723404-978f5800-8f0e-11eb-8c77-cde49523341f.png)

**Comment by julienchabanon** [comment]
Same here

**Comment by Mycroft-Studios** [comment]
You don't "need to use v2", v2 is no where near completed and no esx_* scripts will work with it.

Your problem when using v1 is your database
