### ISSUE TITLE
Locale [%param_228%] does not exist?

### ISSUE THREAD

**Issue by Deraaks** [esx-framework/es_extended#1101]
pls help xD

**Comment by Deraaks** [comment]
![unknown](https://user-images.githubusercontent.com/81644770/113140831-38d91f80-9229-11eb-9f78-1b867345df2a.png)
This is the error

**Comment by Mycroft-Studios** [comment]
What ESX version is this?

**Comment by Deraaks** [comment]
@Mycroft-Studios  it is this https://github.com/zap-fivem/esx

**Comment by Mycroft-Studios** [comment]
Ah, I recommend not using that, and switching to either v1-final and install everything by hand or install plume ESX

**Comment by ESXCrackhead** [comment]
We do not support ZAP, or anything ZAP provides.
