### ISSUE TITLE
ESX 2: mysql-async error, then server crash and restart

### ISSUE THREAD

**Issue by Frede0021** [esx-framework/es_extended#1103]
Hello I am getting a mysql-async error on server startup. it seems to be able to connect to the database because when i disable it I will get a different error.
I am getting this in the consol:
[mysql-async] [ERROR] Packets out of order. Got: 1 Expected: 0

Edit:
I am using MariaDB and I have imported the sql file using heidiSQL. I also tried completely reinstalling MariaDB.

**Comment by Mycroft-Studios** [comment]
That's not an ESX problem, make sure that you are using a mariaDB server though

**Comment by Frede0021** [comment]
> 
> 
> That's not an ESX problem, make sure that you are using a mariaDB server though

I am using the newest version of MariaDB-server on Debian and I can connect to it just fine.

**Comment by Mycroft-Studios** [comment]
> > 
> > 
> > That's not an ESX problem, make sure that you are using a mariaDB server though
> 
> I am using the newest version of MariaDB-server on Debian and I can connect to it just fine.

it's 100% a network error, esx shouldn't have anything todo with the packets

**Comment by Frede0021** [comment]
ok i figured it out. I set the bind-ip in mariaDB to the ip my server has in my network rather than the localhost to remotely access it. I also set the ip correctly in the fivem server.cfg but it doesnt seem to work that way.
