### ISSUE TITLE
Update init SQL file

### ISSUE THREAD

**Issue by MAC-gg** [esx-framework/es_extended#1106]
Hello,

Thanks for these great mods! I just wanted to point out a bug.

Currently, the init SQL file only creates the es_extended database but does not create any tables. To fix the issues that I have, I dug into ESXv1 to grab the old SQL. This has fixed my issues, but I don't know if anything else has changed since the release, and it is technically deprecated code.

Please update this file or give installation instructions that would set up tables for jobs, items, users, etc.

Thanks!

**Comment by Mycroft-Studios** [comment]
no that is intentional

**Comment by Mycroft-Studios** [comment]
ESX 2 creates its own database

**Comment by Mycroft-Studios** [comment]
You shouldnt use v2 unless you are an experienced developer tho since its not finished at all

**Comment by Mycroft-Studios** [comment]
On top of that, the master branch is very very old, the development branch is where the latest v2 is

**Comment by MAC-gg** [comment]
How would I create a table for jobs, users, items, etc? Does it auto set up after running es_extended on the server?

**Comment by Mycroft-Studios** [comment]
> How would I create a table for jobs, users, items, etc? Does it auto set up after running es_extended on the server?

You don't. you just create the database and esx v2 does it all,

v2 does not Include items nor jobs, or anything big like that yet

for esx you should always use v1-final unless you are looking to help develop a core v2 feature

**Comment by MAC-gg** [comment]
Okay, so what you're saying is run ESX v2 with esx_jobs and it will auto-create what is needed?

Or is esx_jobs a v1 mod and shouldn't be used with ESX v2?

**Comment by Mycroft-Studios** [comment]
> Okay, so what you're saying is run ESX v2 with esx_jobs and it will auto-create what is needed?
> 
> Or is esx_jobs a v1 mod and shouldn't be used with ESX v2?

I'm saying **DO NOT USE V2** it is not done, and has no big features

no **esx_** scripts will work with it since its a  completely different framework

if you want to use esx, use **esx v1-final**

**Comment by MAC-gg** [comment]
Okay, thanks! I think others are doing this from issues I've seen on other esx_ mods
