### ISSUE TITLE
ESX V1 Final memory leak

### ISSUE THREAD

**Issue by Mackgame4** [esx-framework/es_extended#1108]
Some months ago i, as i do daily, started my esx server, so i went afk with my server and resmon opened, and when i went back esx was using like 7mb of memory, so i tested out and watched my resmon on es_extended for a while and it just keeps growing and never cleaned, like other resources thats like hitting 600kb it backs to 200kb for example, so im writting this to report an **ESX Memory Leak** that after some time leads to FPS and texture loss, etc, i tried to find some way to fix but couldnt, so theres is my report

- Some things i found: it grows as other resources on command execute like car spawning etc, but never cleaned, and it grows even on idle, like when not making any actions, etc

- Screenshots and Video:
https://streamable.com/qtbs1x

screenshot of memory while i wrote this issue:
![image](https://user-images.githubusercontent.com/42896437/113934695-fa75ce80-97ed-11eb-86ca-cc277a2ac08c.png)
while posting:
![image](https://user-images.githubusercontent.com/42896437/113935578-9dc6e380-97ee-11eb-9782-ab1449162596.png)

PS: i was on a localhost, so no more players, and no one was making any interactions with es_extended

**Comment by TasoOneAsia** [comment]
Can you provide any other metrics regarding memory growth over time? Considering nobody else has reported an issue like this before officially, I'll need to cross reference this with some production environments.

**Comment by Mackgame4** [comment]
PS: fresh installed esx v1, fivem build 2060, only es_extended sql, all es_extended installation guide followed, no console client and server side errors, only have fivem cfx-data mysql-async, async, esx_menus and es_extended installed

**Comment by Mycroft-Studios** [comment]
then that is a issue on your end, if it happens on multiple frameworks

**Comment by ESXCrackhead** [comment]
ESX1 is not supported on the Github, but you are welcome to discuss this issue on the Discord.
