### ISSUE TITLE
[Legacy] Randomly spawning as invisible

### ISSUE THREAD

**Issue by d3rp-jsx** [esx-framework/es_extended#1172]
## Issue Checklist

- [x] I'm using the latest version (legacy branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

**_Player ped spawning normally_**

## Current Result

**_Player ped randomly spawning as invisible_**

## How to reproduce the problem

1. **_Freshly cloned es_extended, esx_skin, esx_identity, skinchanger and strictly needed dependencies_**
2. **_Join the server multiple times until you spawn invisible (it's not hard in my case, 50/50)_**

Useful information: **_I'm on debian, latest artifact everything is installed properly and actually everything else is working perfectly as expected, this is the only issue._**

A workaround that may help in solving: **_Using /skin and closing the skin menu right after will spawn the skin_**

## Errors

`No server or client errors`

**Comment by thelindat** [comment]
This is, as far as I am aware, not an issue in the coming update.
`git clone -b multichar https://github.com/thelindat/es_extended.git`

If it does happen with that version then I'll look into it.

**Comment by d3rp-jsx** [comment]
This actually seems to be fixed in your branch, I'll test this deeper and let you know if it happens again.

**Comment by d3rp-jsx** [comment]
I can confirm after days of testing this is solved and never happened again with multichar branch,
