### ISSUE TITLE
[Legacy] Clear loadout command not working properly

### ISSUE THREAD

**Issue by d3rp-jsx** [esx-framework/es_extended#1175]
## Issue Checklist

- [x] I'm using the latest version (legacy and multichar branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

**_'/clearloadout [id]' to clear the whole loadout at once._**

## Current Result

**_'/clearloadout [id]' only clearing part of the loadout; you have to execute the command multiple times to get the loadout completely clear._**

## How to reproduce the problem

1. **_Clean install of es_extended with basic requirements_**
2. **_Give yourself multiple weapons (pistol, assault rifle, rpg...)_**
3. **_Test '/clearloadout [id]'_**

## Errors

`No errors at all.`

### Possible Solution

**_Even though the loop seems to be good at first sight (it printed all the weapons when I tried to debug it), for some reason it feels like when you execute the command it won't loop through the whole loadout._**

**Comment by thelindat** [comment]
```lua
ESX.RegisterCommand('clearloadout', 'admin', function(xPlayer, args, showError)
	for i=1, #args.playerId.loadout do
		args.playerId.removeWeapon(args.playerId.loadout[1].name)
	end
end, true, {help = _U('command_clearloadout'), validate = true, arguments = {
	{name = 'playerId', help = _U('commandgeneric_playerid'), type = 'player'}
}})
```

A cheap and nasty solution.. but the whole command can be changed rather than triggering all these functions and events.

**Comment by d3rp-jsx** [comment]
It's working, is this issue due to the loadout table indexes being updated at every removeWeapon()? I didn't fully understand the problem here honestly.

**Comment by thelindat** [comment]
Honestly at a glance it looks fine, but yeah I suppose the changing index causes it to break. Either doing it as above, or changing the function itself to set the index as nil (instead of using table.remove) works.

This is how the command worked prior to ESX 1.2
```lua
for i=#xPlayer.loadout, 1, -1 do
	xPlayer.removeWeapon(xPlayer.loadout[i].name)
end
```
Which probably makes more sense than how I fixed it, but the result is the same.

**Comment by thelindat** [comment]
```
ESX.RegisterCommand('clearloadout', 'admin', function(xPlayer, args, showError)
	for i=#args.playerId.loadout, 1, -1 do
		xPlayer.removeWeapon(args.playerId.loadout[i].name)
	end
end, true, {help = _U('command_clearloadout'), validate = true, arguments = {
	{name = 'playerId', help = _U('commandgeneric_playerid'), type = 'player'}
}})
```

Going with the old version of the command for the PR. Thanks for all your bug reports.

**Comment by d3rp-jsx** [comment]
Probably more like this?

```lua
ESX.RegisterCommand('clearloadout', 'admin', function(xPlayer, args, showError)
	for i=#args.playerId.loadout, 1, -1 do
		args.playerId.removeWeapon(args.playerId.loadout[i].name)
	end
end, true, {help = _U('command_clearloadout'), validate = true, arguments = {
	{name = 'playerId', help = _U('commandgeneric_playerid'), type = 'player'}
}})
```

**Comment by thelindat** [comment]
I'm leaving typos everywhere today.
