### ISSUE TITLE
[Legacy] Weapon ammo not saving properly

### ISSUE THREAD

**Issue by d3rp-jsx** [esx-framework/es_extended#1176]
## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (legacy and multicharbranch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

**_Weapon ammo to be correctly updated after player is saved._**

## Current Result

**_After saving the player, weapon ammo is not updated, the initial value is stored instead._**

## How to reproduce the problem

1. **_Give yourself a weapon with, let's say, 100 ammo_**
2. **_Waste some bullets_**
3. **_Save the player_**
4. **_Check database or re-log into the server and see that ammos are back to 100_**

## Errors

`No errors at all.`

### Possible Solution

**_Around line 370 in client/main.lua, right after StartServerSyncLoops function opening:_**

```
Citizen.CreateThread(function()
        while ESX.PlayerLoaded do
	        Citizen.Wait(0)
	        if IsPedArmed(ESX.PlayerData.ped, 4) then
		        if IsPedShooting(ESX.PlayerData.ped) then
			        local _,weaponHash = GetCurrentPedWeapon(ESX.PlayerData.ped, true)
			        local weapon = ESX.GetWeaponFromHash(weaponHash)

			        if weapon then
				        local ammoCount = GetAmmoInPedWeapon(ESX.PlayerData.ped, weaponHash)
				        TriggerServerEvent('esx:updateWeaponAmmo', weapon.name, ammoCount)
			        end
		        end
	        end
        end
end)
```

**_The problem is that IsPedShooting() is not triggering unless it's not called every frame so you can't let sleep this thread at all. Code above is the already fixed one._**

**Comment by thelindat** [comment]
Would you care to try the following code? This slows down the loop and prevents it from sending a server event every time the player shoots; instead it sets a timer to 100ms on every shot, triggering once the shooting has stopped.

```lua
	-- keep track of ammo
	Citizen.CreateThread(function()
		local currentWeapon = {timer=0}
		while ESX.PlayerLoaded do
			local sleep = 5

			if currentWeapon.timer == sleep then
				local ammoCount = GetAmmoInPedWeapon(ESX.PlayerData.ped, currentWeapon.hash)
				TriggerServerEvent('esx:updateWeaponAmmo', currentWeapon.name, ammoCount)
				currentWeapon.timer = 0
			elseif currentWeapon.timer > sleep then
				currentWeapon.timer = currentWeapon.timer - sleep
			end

			if IsPedArmed(ESX.PlayerData.ped, 4) then
				if IsPedShooting(ESX.PlayerData.ped) then
					local _,weaponHash = GetCurrentPedWeapon(ESX.PlayerData.ped, true)
					local weapon = ESX.GetWeaponFromHash(weaponHash)

					if weapon then
						currentWeapon.name = weapon.name
						currentWeapon.hash = weaponHash	
						currentWeapon.timer = 100 * sleep		
					end
				end
			else
				sleep = 200
			end
			Citizen.Wait(sleep)
		end
	end)
```

**Comment by d3rp-jsx** [comment]
> Would you care to try the following code? This slows down the loop and prevents it from sending a server event every time the player shoots; instead it sets a timer to 100ms on every shot, triggering once the shooting has stopped.
> 
> ```lua
> 	-- keep track of ammo
> 	Citizen.CreateThread(function()
> 		local currentWeapon = {timer=0}
> 		while ESX.PlayerLoaded do
> 			local sleep = 5
> 
> 			if currentWeapon.timer == sleep then
> 				local ammoCount = GetAmmoInPedWeapon(ESX.PlayerData.ped, currentWeapon.hash)
> 				TriggerServerEvent('esx:updateWeaponAmmo', currentWeapon.name, ammoCount)
> 				currentWeapon.timer = 0
> 			elseif currentWeapon.timer > sleep then
> 				currentWeapon.timer = currentWeapon.timer - sleep
> 			end
> 
> 			if IsPedArmed(ESX.PlayerData.ped, 4) then
> 				if IsPedShooting(ESX.PlayerData.ped) then
> 					local _,weaponHash = GetCurrentPedWeapon(ESX.PlayerData.ped, true)
> 					local weapon = ESX.GetWeaponFromHash(weaponHash)
> 
> 					if weapon then
> 						currentWeapon.name = weapon.name
> 						currentWeapon.hash = weaponHash	
> 						currentWeapon.timer = 100 * sleep		
> 					end
> 				end
> 			else
> 				sleep = 200
> 			end
> 			Citizen.Wait(sleep)
> 		end
> 	end)
> ```

Working and nice idea!
