### ISSUE TITLE
Camera is in heaven/sky when accessing clotheshop(esx_clotheshop)

### ISSUE THREAD

**Issue by khaizer2277** [esx-framework/es_extended#1177]
## Bug Report
> Please use the template below and replace all example lines with your issue!
Camera is in heaven/sky when accessing clotheshop(esx_clotheshop)

## Issue Checklist
> Please put `x` inside of the box that matches your issue.
- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result
> In a few short sentences please tell us what the expected result / correct behaviour should occur.
the camera should be position in front of the character not in the sky

## Current Result
> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).
The camera is in heaven/sky. I can only see is clouds

## How to reproduce the problem
> What steps did you take for the issue to occur? What would we have to do for the same result to happen?
1. When I update my es_extended then it happened

## Errors
> Screenshot or direct copy and paste of the error from the console window.
No error

### Code Block referenced by the error
> If the code references a specific line of code within a file, what line is it?

### Possible Solution
> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.
I think it is in client/functions.lua of es_extended the line 312 i think the vector something

**Comment by thelindat** [comment]
Ensure you are using the latest version of [esx_skin](https://github.com/esx-framework/esx_skin)
