### ISSUE TITLE
Inventory fails to open 

### ISSUE THREAD

**Issue by ahmetabdi** [esx-framework/es_extended#812]
Version 2

https://i.imgur.com/lWHP5fo.png

**Comment by filipecamargo10** [comment]
same here

**Comment by benpegas** [comment]
This is normal, the menu UI is not yet implemented but will soon be present.

**Comment by Salto4501** [comment]
My inventory no longer opens after the death of a player? (All my menu Ex; F2, F7 etc.)

**Comment by Lemonita66** [comment]
I have te same problem after i die i cant open my inventory anymore

**Comment by itschip** [comment]
I will look into it. Closing this for now.
