### ISSUE TITLE
stucking into intro and getting double ID

### ISSUE THREAD

**Issue by jpedror1005** [esx-framework/es_extended#815]
Hi guys i’m trying to install this lastest update of Es_extended on my brand new server. Unfortunately es extended is giving this error when i try to start the sever and i dont have any idea where it comes from. The issue is that i’m stuck at servers loading screen and cant get in server.

I post my console error and server.cfg file. Hope you can help me out because im not figuring what am i doing wrong or if it is just an issue.

![image](https://user-images.githubusercontent.com/50817343/83330560-a02fe700-a287-11ea-92e0-f217cb99662b.png)  
![image](https://user-images.githubusercontent.com/50817343/83330566-ac1ba900-a287-11ea-9e3a-76be56c271a6.png)
![image](https://user-images.githubusercontent.com/50817343/83330568-b178f380-a287-11ea-9a50-872bd235ed70.png)

**Comment by promoreira** [comment]
Same here, the loading screen you can disable it in fxmanifest.lua. I loved this new loading screen but no way to work woth it until they fix it.

**Comment by Fedefreez** [comment]
I had the same problem. I just disabled the loading screen and now it works.

**Comment by promoreira** [comment]
Any idea how to fix Error loading script server/main.lua in resource esx_skin: @esx_skin/server/main.lua:38: attempt to index a nil value (global 'ESX'), ?

**Comment by filipecamargo10** [comment]
> Any idea how to fix Error loading script server/main.lua in resource esx_skin: @esx_skin/server/main.lua:38: attempt to index a nil value (global 'ESX'), ?

same here

**Comment by jpedror1005** [comment]
> Same here, the loading screen you can disable it in fxmanifest.lua. I loved this new loading screen but no way to work with it until they fix it.

wich line u mean to delete in fxmanifest.lua to disable loading screen? i dont seem to figure out what's the loading screen i dont seem to see nothing related to it !

**Comment by abdulkadiraktas** [comment]
esx 1.x version and all esx_* scripts are deprecated
These scripts are not working with esxv2

**Comment by deviljin112** [comment]
Loadscreen is work in progress, was added as a little detail. But i will be reworking the issues in my free time. We are aware of the loadscreen problems!
