### ISSUE TITLE
Bug creation de table sous MySQL-5.7.24 

### ISSUE THREAD

**Issue by Linedev-Web** [esx-framework/es_extended#828]
### Installation d'un nouveau projet avec les prérequis + Basse de donner MySQL - 5.7.24
_Voici les erreurs obtenu quand je lance le projet:_

identities:
`[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `identities` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64) DEFAULT UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFAULT '{"y":-955.3,"x":-269.4,"heading":205.8,"z":31.2}',
  `first_name` VARCHAR(32) DEFAULT NULL,
  `last_name` VARCHAR(32) DEFAULT NULL,
  `dob` VARCHAR(10) DEFAULT NULL,
  `is_male` INT DEFAULT 1,
  `roles` MEDIUMTEXT DEFAULT '[]',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'identifier', 'VARCHAR(64) DEFAULT UUID() NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'owner', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'position', 'VARCHAR(255) DEFAULT \'{"y":-955.3,"x":-269.4,"heading":205.8,"z"
:31.2}\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'first_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'last_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'dob', 'VARCHAR(10) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'is_male', 'INT DEFAULT 1');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
": ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right
syntax to use near 'UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFA' at line 3
`

players:

[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `players` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64)  NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `identity_id` VARCHAR(64) DEFAULT NULL,
  `roles` MEDIUMTEXT DEFAULT '[]',
  `accessories` MEDIUMTEXT DEFAULT '{}',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identifier', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'name', 'VARCHAR(255) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identity_id', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'accessories', 'MEDIUMTEXT DEFAULT \'{}\'');
": ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'roles' can't have a default value

**Comment by Faridstarky** [comment]
C'est une erreur mysql quand tu essaye de upload la nouvelle base de donnée ? a tu un screen ?

**Comment by izio38** [comment]
We are aware of this issue, @Linedev-Web too.

Consider this ticket as a bug tracker.

**Comment by Linedev-Web** [comment]
Yes, it is at the creation of the project that I get this error.

**Comment by izio38** [comment]
For now (untill we resolve the bug), you'll have to install MariaDB instead of MySQL.

**Comment by Linedev-Web** [comment]
Yes, I did, and it worked perfectly as you advised.
