### ISSUE TITLE
problems with linux

### ISSUE THREAD

**Issue by esra4** [esx-framework/es_extended#834]
I'm running the server on linux with this addon and it stays on the loading screen.

I've entered the fivem from 0 and I've entered es_extended, mysql-async, async, cron and skinchanger.

but it doesn't go past the loading screen.

Help please :S

**Comment by z4q** [comment]
v1 or v2

**Comment by esra4** [comment]
V2

**Comment by z4q** [comment]
already run npm install in es_extended?

**Comment by nloyola** [comment]
I'm having the same issue. Is there a fix? Thank you.

I'm running from what is in the master branch.

**Comment by esra4** [comment]
@z4q npm install? 

npm WARN enoent ENOENT: no such file or directory, open prueba/resources/es_extended/package.json'
npm WARN es_extended No description
npm WARN es_extended No repository field.
npm WARN es_extended No README data
npm WARN es_extended No license field.

**Comment by z4q** [comment]
try put ensure async in server.cfg or better change to develop and run npm install there

**Comment by itschip** [comment]
You need a package.json. Do npm init to install that.

**Comment by OnyxExeption** [comment]
I did I get this error: **npm WARN es_extended@1.0.0 No repository field.**
