### ISSUE TITLE
es_extended

### ISSUE THREAD

**Issue by rhcore30** [esx-framework/es_extended#840]
empty es_extended.sql

**Comment by z4q** [comment]
v2 will do automate db thing. called migration

**Comment by PhillTV** [comment]
What do you mean? i have the same problem. Do you have a Tutorial?

**Comment by TrinxudasDoZe** [comment]
> What do you mean? i have the same problem. Do you have a Tutorial?

It says it on the readme. The factions example, it automatically creates a faction column on the users table, that's the db generation automated.
