### ISSUE TITLE
Error create table by MariaDB 10.4.13

### ISSUE THREAD

**Issue by k88968896** [esx-framework/es_extended#843]
[MariaDB:10.4.13-MariaDB] [Slow Query Warning] [es_extended] [217ms] CREATE TABLE IF NOT EXISTS `identities` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64) DEFAULT UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFAULT '{"heading":205.8,"z":31.2,"y":-955.3,"x":-269.4}',
  `first_name` VARCHAR(32) DEFAULT NULL,
  `last_name` VARCHAR(32) DEFAULT NULL,
  `dob` VARCHAR(10) DEFAULT NULL,
  `is_male` INT DEFAULT 1,
  `roles` MEDIUMTEXT DEFAULT '[]',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'identifier', 'VARCHAR(64) DEFAULT UUID() NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'owner', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'position', 'VARCHAR(255) DEFAULT \'{"heading":205.8,"z":31.2,"y":-955.3,"x":-269.4}\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'first_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'last_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'dob', 'VARCHAR(10) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'is_male', 'INT DEFAULT 1');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');

**Comment by izio38** [comment]
This is a warning, nothing you should be worried of. This is executed only the first time you're starting the server
