### ISSUE TITLE
Error During Loading

### ISSUE THREAD

**Issue by amrizama** [esx-framework/es_extended#845]
> `[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `accounts` (
  `name` VARCHAR(255)  NOT NULL,
  `owner` VARCHAR(64) DEFAULT NULL,
  `money` int DEFAULT 0 NOT NULL,
  PRIMARY KEY(`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

> `call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'name', 'VARCHAR(255)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'owner', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'money', 'int DEFAULT 0 NOT NULL');
": ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `datastores` (
  `name` VARCHAR(255)  NOT NULL,
  `owner` VARCHAR(64) DEFAULT NULL,
  `data` LONGTEXT ,
  PRIMARY KEY(`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

> `call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'datastores', 'name', 'VARCHAR(255)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'datastores', 'owner', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'datastores', 'data', 'LONGTEXT ');
": ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT > > > EXISTS `inventories` (
> `  `name` VARCHAR(255)  NOT NULL,
> `  `owner` VARCHAR(64) DEFAULT NULL,
> `  `items` LONGTEXT DEFAULT NULL,
> `  PRIMARY KEY(`name`)
> `) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

> `call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'name', 'VARCHAR(255)  NOT > NULL');
> `call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'owner', 'VARCHAR(64) DEFAULT > NULL');
> `call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'items', 'LONGTEXT DEFAULT NULL');
> `": ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
> `[esx] [migrate] ensuring migrations
> `[esx] [player] starting db sync
> `[esx] server ready
> `[esx] [player] new db accessor => DOB | dob
> `[esx] [player] new db accessor => accessories | accessories
> `[esx] [player] new db accessor => firstName | first_name
> `[esx] [player] new db accessor => isMale | is_male
> `[esx] [player] new db accessor => lastName | last_name
> `[esx] [inventory] new inventory => test
> `[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "SELECT * FROM > > inventories WHERE name = 'test'": ER_NO_SUCH_TABLE: Table 'base.inventories' doesn't exist
> `SCRIPT ERROR: es_extended:modules/__core__/inventory/server/module.lua:63: attempt to index > `a nil value (local 'rows')
> `> ref (es_extended:modules/__core__/inventory/server/module.lua:63)
> `>  (@mysql-async/mysql-async.js:15916)
> `Sending heartbeat to https://servers-ingress-live.fivem.net/ingress`

Bonjour, 

Je viens de creer un serveur, et lors de l'iniatilisation de Ex_extended j'ai cette erreur, j'ai vérifié ma base de données et la plupart des tables affichés comme absente sont bel et bien présentes ... je suis un peu perdu sachant que le fichier SQL est totalement vide, Cependant j'ai lu que c'etait normal car il creer de manière automatique les tables necessaires a son fonctionnement mais apparament la non .....

Cordialement , 
A

**Comment by izio38** [comment]
Please use develop branch for now and read the readme. Make sure you're using MariaDb
