### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by OnyxExeption** [esx-framework/es_extended#846]
Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x ] I'm using the latest version.
- [ x] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [ x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

Hello, If I join with my account on my FiveM Server I stuck in the loading Screen.
In the "F8 Console" I got 3 error with es_extended

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. Install es_extended how its descriped in the README
2. Start es_extended
3. Join on the Server and show in the F8 Console

## Errors

![2020-06-14 10_42_37-](https://user-images.githubusercontent.com/39564156/84588979-e1013180-ae2b-11ea-863a-d6f7bccbd3ba.png)
![2020-06-14 10_42_46-](https://user-images.githubusercontent.com/39564156/84588981-e3638b80-ae2b-11ea-8c80-af8dcc34ea9a.png)

`[     53469] [    GTAProcess]             MainThrd/ Creating script environments for es_extended
[     53516] [    GTAProcess]             MainThrd/ Error loading script boot/client/events.lua in resource es_extended: @es_extended/boot/shared/module.lua:32: attempt to get length of a nil value (local 't')
[     53532] [    GTAProcess]             MainThrd/ stack traceback:
[     53532] [    GTAProcess]             MainThrd/ 	@es_extended/boot/shared/module.lua:32: in upvalue 'tableIndexOf'
[     53532] [    GTAProcess]             MainThrd/ 	@es_extended/boot/shared/module.lua:165: in field 'IsCoreModule'
[     53547] [    GTAProcess]             MainThrd/ 	@es_extended/boot/shared/module.lua:223: in function 'M'
[     53547] [    GTAProcess]             MainThrd/ 	@es_extended/boot/client/events.lua:16: in main chunk
[     53547] [    GTAProcess]             MainThrd/ Failed to load script boot/client/events.lua.
[     53563] [    GTAProcess]             MainThrd/ Error loading script boot/shared/main.lua in resource es_extended: @es_extended/boot/shared/main.lua:16: attempt to get length of a nil value (field 'CoreEntries')
[     53563] [    GTAProcess]             MainThrd/ stack traceback:
[     53563] [    GTAProcess]             MainThrd/ 	@es_extended/boot/shared/main.lua:16: in main chunk
[     53594] [    GTAProcess]             MainThrd/ Failed to load script boot/shared/main.lua.
[     53594] [    GTAProcess]             MainThrd/ Error loading script boot/client/main.lua in resource es_extended: @es_extended/boot/shared/module.lua:32: attempt to get length of a nil value (local 't')
[     53610] [    GTAProcess]             MainThrd/ stack traceback:
[     53610] [    GTAProcess]             MainThrd/ 	@es_extended/boot/shared/module.lua:32: in upvalue 'tableIndexOf'
[     53610] [    GTAProcess]             MainThrd/ 	@es_extended/boot/shared/module.lua:165: in field 'IsCoreModule'
[     53625] [    GTAProcess]             MainThrd/ 	@es_extended/boot/shared/module.lua:223: in function 'M'
[     53625] [    GTAProcess]             MainThrd/ 	@es_extended/boot/client/main.lua:15: in main chunk
[     53625] [    GTAProcess]             MainThrd/ Failed to load script boot/client/main.lua.
[     53625] [    GTAProcess]             MainThrd/ Still executing script initialization routines...`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`**for i=1, #self.CoreEntries, 1 do**

  local name = self.CoreEntries[i]

  if self.ModuleHasEntryPoint(name, true) then

    local module, _error = self.LoadModule(name, true)

    if _error then
      hasError = true
      break
    end

  end

end`

`local tableIndexOf = function(t, val)

  **for i=1, #t, 1 do**
    if t[i] == val then
      return i
    end
  end

  return -1

end`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

Dont use ESX

**Comment by OnyxExeption** [comment]
And I tried to disable the ESX Loadscreen but Its still there ;)

**Comment by OnyxExeption** [comment]
And If this Error happens because the FX Server Version, then write in the README this version what we need

**Comment by z4q** [comment]
please use develop branch. and run yarn (node v10)

**Comment by OnyxExeption** [comment]
Okay I did, and now I get this in my Console:

`[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `identities` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64) DEFAULT UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFAULT '{"x":-269.40000000002,"y":-955.30000000004,"z":31.199999999998,"heading":205.79999999998}',
  `first_name` VARCHAR(32) DEFAULT NULL,
  `last_name` VARCHAR(32) DEFAULT NULL,
  `dob` VARCHAR(10) DEFAULT NULL,
  `is_male` INT DEFAULT 1,
  `roles` MEDIUMTEXT DEFAULT '[]',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'identifier', 'VARCHAR(64) DEFAULT UUID() NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'owner', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'position', 'VARCHAR(255) DEFAULT \'{"x":-269.40000000002,"y":-955.30000000004,"z":31.199999999998,"heading":205.79999999998}\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'first_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'last_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'dob', 'VARCHAR(10) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'is_male', 'INT DEFAULT 1');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
": ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFA' at line 3
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64)  NOT NULL,
  `owner` VARCHAR(64) DEFAULT NULL,
  `money` INT DEFAULT 0,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'name', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'owner', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'money', 'INT DEFAULT 0');
": ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'sql-esxServer.accounts ADD COLUMN id INT  NOT NULL AUTO_INCREMENT' at line 1
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "CREATE TABLE IF NOT EXISTS `players` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64)  NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `identity_id` VARCHAR(64) DEFAULT NULL,
  `roles` MEDIUMTEXT DEFAULT '[]',
  `accessories` MEDIUMTEXT DEFAULT '{}',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identifier', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'name', 'VARCHAR(255) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identity_id', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'accessories', 'MEDIUMTEXT DEFAULT \'{}\'');
": ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'roles' can't have a default value´

**Comment by HavannaFR** [comment]
Same problem here, you found a fix ?

**Comment by izio38** [comment]
Mysql isn't supported and won't be supported. if you want to know why : #839 
Please use MariaDb
