### ISSUE TITLE
Weird errors in console please help

### ISSUE THREAD

**Issue by jdve1999** [esx-framework/es_extended#847]
I get these errors in my console when starting my fivem server. I have no single idea what i did wrong and i can't find any information out of it. Could someone help?

[MariaDB:10.4.8-MariaDB] [Slow Query Warning] [es_extended] [447ms] CREATE TABLE IF NOT EXISTS `migrations` (
  `id` INT(11)  NOT NULL AUTO_INCREMENT,
  `module` VARCHAR(64) ,
  `last` INT(11) ,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'migrations', 'id', 'INT(11)  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'migrations', 'module', 'VARCHAR(64) ');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'migrations', 'last', 'INT(11) ');

[MariaDB:10.4.8-MariaDB] [Slow Query Warning] [es_extended] [464ms] CREATE TABLE IF NOT EXISTS `job_grades` (
  `id` INT(11)  NOT NULL AUTO_INCREMENT,
  `job_name` VARCHAR(32) ,
  `grade` INT  NOT NULL,
  `name` VARCHAR(64)  NOT NULL,
  `label` VARCHAR(64)  NOT NULL,
  `salary` INT  NOT NULL,
  `skin_male` LONGTEXT  NOT NULL,
  `skin_female` LONGTEXT  NOT NULL,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'id', 'INT(11)  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'job_name', 'VARCHAR(32) ');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'grade', 'INT  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'name', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'label', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'salary', 'INT  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'skin_male', 'LONGTEXT  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'job_grades', 'skin_female', 'LONGTEXT  NOT NULL');

[MariaDB:10.4.8-MariaDB] [Slow Query Warning] [es_extended] [696ms] CREATE TABLE IF NOT EXISTS `users` (
  `identifier` VARCHAR(40)  NOT NULL,
  `name` LONGTEXT DEFAULT NULL,
  `accounts` LONGTEXT DEFAULT NULL,
  `group` VARCHAR(64) DEFAULT 'user',
  `inventory` LONGTEXT DEFAULT NULL,
  `job` VARCHAR(32) DEFAULT 'unemployed',
  `job_grade` INT DEFAULT 0,
  `loadout` LONGTEXT DEFAULT NULL,
  `position` VARCHAR(255) DEFAULT '{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}',
  `is_dead` INT DEFAULT 0,
  `last_name` VARCHAR(32) DEFAULT NULL,
  `dob` VARCHAR(10) DEFAULT NULL,
  `is_male` INT DEFAULT 1,
  `accessories` MEDIUMTEXT DEFAULT NULL,
  `first_name` VARCHAR(32) DEFAULT NULL,
  PRIMARY KEY(`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'identifier', 'VARCHAR(40)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'name', 'LONGTEXT DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'accounts', 'LONGTEXT DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'group', 'VARCHAR(64) DEFAULT \'user\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'inventory', 'LONGTEXT DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'job', 'VARCHAR(32) DEFAULT \'unemployed\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'job_grade', 'INT DEFAULT 0');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'loadout', 'LONGTEXT DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'position', 'VARCHAR(255) DEFAULT \'{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'is_dead', 'INT DEFAULT 0');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'last_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'dob', 'VARCHAR(10) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'is_male', 'INT DEFAULT 1');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'accessories', 'MEDIUMTEXT DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'users', 'first_name', 'VARCHAR(32) DEFAULT NULL');

[MariaDB:10.4.8-MariaDB] [Slow Query Warning] [es_extended] [293ms] CREATE TABLE IF NOT EXISTS `accounts` (
  `name` VARCHAR(255)  NOT NULL,
  `owner` VARCHAR(64) DEFAULT NULL,
  `money` int DEFAULT 0 NOT NULL,
  PRIMARY KEY(`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'name', 'VARCHAR(255)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'owner', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'accounts', 'money', 'int DEFAULT 0 NOT NULL');

[MariaDB:10.4.8-MariaDB] [Slow Query Warning] [es_extended] [244ms] CREATE TABLE IF NOT EXISTS `items` (
  `name` VARCHAR(64)  NOT NULL,
  `label` VARCHAR(64)  NOT NULL,
  `weight` INT  NOT NULL,
  `rare` INT  NOT NULL,
  `can_remove` INT  NOT NULL,
  PRIMARY KEY(`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'items', 'name', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'items', 'label', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'items', 'weight', 'INT  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'items', 'rare', 'INT  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'items', 'can_remove', 'INT  NOT NULL');

**Comment by keketiger** [comment]
Hello, @jdve1999 this is not an error, but rather information. It informs you that some tables are missing in your database and that it will therefore create them, but the SQL queries are slow.

If you restart your server after this, there should no longer be these messages.

**Comment by jdve1999** [comment]
> Hello, @jdve1999 this is not an error, but rather information. It informs you that some tables are missing in your database and that it will therefore create them, but the SQL queries are slow.
> 
> If you restart your server after this, there should no longer be these messages.

I get this same information everytime. Nothin happens in the database

**Comment by daMairis** [comment]
If you are hosting a server on your own hosting, then you do not have to worry about these errors.
The error is due to poorly optimized database tables/rows.
