### ISSUE TITLE
resourcce time warning

### ISSUE THREAD

**Issue by chidoman321** [esx-framework/es_extended#850]
# Template

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ x] I'm using the latest version.
- [x ] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [x ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> no warning

## Current Result

> 
![image](https://user-images.githubusercontent.com/49621062/85214388-ee845300-b326-11ea-90af-5db72ad92d13.png)

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

run server/ wait some time

**Comment by deviljin112** [comment]
You are not using "latest version", ESX 2 does not use esx_menu_* instead these are modules. You are most likely using 1.2, and that can be caused by a poorly written script, not necessarily by es_extended.

**Comment by chidoman321** [comment]
![image](https://user-images.githubusercontent.com/49621062/85233773-2c848400-b3c6-11ea-8051-87c8958265e0.png)

**Comment by chidoman321** [comment]
i follow this guide https://esx-org.github.io/installation/

i should have esx attempt to index nil value global(ESX) , with this resources ?
start esx_menu_default
start esx_menu_list
start esx_menu_dialog

**Comment by chidoman321** [comment]
sorry then i will send de issue for the resources repo

**Comment by deviljin112** [comment]
You are using 2.0 with 1.2 scripts these are not compatible, you should get an error with index value ESX as object doesnt exist anymore.
