### ISSUE TITLE
Installation Ubuntu 18.04 > MariaDB > es_extended develop branch > Syntax Errors when trying to launch.

### ISSUE THREAD

**Issue by GizmoDevs** [esx-framework/es_extended#851]
## Issue Checklist

- [* ] I'm using the latest version.
- [*] The issue has occured more than once.
- [*] I have followed the readme and my setup is correct.
- [*] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [*] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

Expected automated migrations to work.

## Current Result

Syntax seems to be incorrect for MariaDB which is what you are saying MUST be used for the develop branch installation.

## How to reproduce the problem

Stop Server
Start Server

## Errors
`
[esx/core/db] ensuring generated schemas
[esx/core/db] table accounts (id, name, owner, money)
[esx/core/db] table identities (id, identifier, owner, position, first_name, last_name, dob, is_male, roles)
[esx/core/db] table inventories (name, owner, items)
[esx/core/db] table migrations (id, module, last)
[esx/core/db] table players (id, identifier, name, identity_id, roles, accessories)
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [3ms] SHOW TABLES LIKE 'migrations' : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [8ms] CREATE TABLE IF NOT EXISTS `migrations` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `module` VARCHAR(64) ,
  `last` INT(11) ,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'migrations', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'migrations', 'module', 'VARCHAR(64) ');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'migrations', 'last', 'INT(11) ');
 : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [3ms] SHOW TABLES LIKE 'inventories' : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [7ms] CREATE TABLE IF NOT EXISTS `inventories` (
  `name` VARCHAR(255)  NOT NULL,
  `owner` VARCHAR(64) DEFAULT NULL,
  `items` LONGTEXT DEFAULT NULL,
  PRIMARY KEY(`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'name', 'VARCHAR(255)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'owner', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'items', 'LONGTEXT DEFAULT NULL');
 : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [ERROR] [es_extended] An error happens for query "CREATE TABLE IF NOT EXISTS `inventories` (
  `name` VARCHAR(255)  NOT NULL,
  `owner` VARCHAR(64) DEFAULT NULL,
  `items` LONGTEXT DEFAULT NULL,
  PRIMARY KEY(`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'name', 'VARCHAR(255)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'owner', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'inventories', 'items', 'LONGTEXT DEFAULT NULL');
 : []": ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [3ms] SHOW TABLES LIKE 'players' : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [2ms] CREATE TABLE IF NOT EXISTS `players` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64)  NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `identity_id` VARCHAR(64) DEFAULT NULL,
  `roles` MEDIUMTEXT DEFAULT '[]',
  `accessories` MEDIUMTEXT DEFAULT '{}',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identifier', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'name', 'VARCHAR(255) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identity_id', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'accessories', 'MEDIUMTEXT DEFAULT \'{}\'');
 : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [ERROR] [es_extended] An error happens for query "CREATE TABLE IF NOT EXISTS `players` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64)  NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `identity_id` VARCHAR(64) DEFAULT NULL,
  `roles` MEDIUMTEXT DEFAULT '[]',
  `accessories` MEDIUMTEXT DEFAULT '{}',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identifier', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'name', 'VARCHAR(255) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'identity_id', 'VARCHAR(64) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'players', 'accessories', 'MEDIUMTEXT DEFAULT \'{}\'');
 : []": ER_BLOB_CANT_HAVE_DEFAULT: BLOB/TEXT column 'roles' can't have a default value
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [1ms] SHOW TABLES LIKE 'identities' : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [es_extended] [2ms] CREATE TABLE IF NOT EXISTS `identities` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64) DEFAULT UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFAULT '{"z":31.199999999998,"heading":205.79999999998,"x":-269.40000000002,"y":-955.30000000004}',
  `first_name` VARCHAR(32) DEFAULT NULL,
  `last_name` VARCHAR(32) DEFAULT NULL,
  `dob` VARCHAR(10) DEFAULT NULL,
  `is_male` INT DEFAULT 1,
  `roles` MEDIUMTEXT DEFAULT '[]',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'identifier', 'VARCHAR(64) DEFAULT UUID() NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'owner', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'position', 'VARCHAR(255) DEFAULT \'{"z":31.199999999998,"heading":205.79999999998,"x":-269.40000000002,"y":-955.30000000004}\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'first_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'last_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'dob', 'VARCHAR(10) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'is_male', 'INT DEFAULT 1');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
 : []
[MariaDB:10.1.44-MariaDB-0ubuntu0.18.04.1] [ERROR] [es_extended] An error happens for query "CREATE TABLE IF NOT EXISTS `identities` (
  `id` INT  NOT NULL AUTO_INCREMENT,
  `identifier` VARCHAR(64) DEFAULT UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFAULT '{"z":31.199999999998,"heading":205.79999999998,"x":-269.40000000002,"y":-955.30000000004}',
  `first_name` VARCHAR(32) DEFAULT NULL,
  `last_name` VARCHAR(32) DEFAULT NULL,
  `dob` VARCHAR(10) DEFAULT NULL,
  `is_male` INT DEFAULT 1,
  `roles` MEDIUMTEXT DEFAULT '[]',
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'id', 'INT  NOT NULL AUTO_INCREMENT');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'identifier', 'VARCHAR(64) DEFAULT UUID() NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'owner', 'VARCHAR(64)  NOT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'position', 'VARCHAR(255) DEFAULT \'{"z":31.199999999998,"heading":205.79999999998,"x":-269.40000000002,"y":-955.30000000004}\'');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'first_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'last_name', 'VARCHAR(32) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'dob', 'VARCHAR(10) DEFAULT NULL');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'is_male', 'INT DEFAULT 1');
call ADD_COLUMN_IF_NOT_EXISTS(DATABASE(), 'identities', 'roles', 'MEDIUMTEXT DEFAULT \'[]\'');
 : []": ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UUID() NOT NULL,
  `owner` VARCHAR(64)  NOT NULL,
  `position` VARCHAR(255) DEFA' at line 3`
`

### server.cfg

`endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"
sv_listingIPOverride "ipenteredhere"

sv_licenseKey "keyenteredhere"
set steam_webApiKey "keyenteredhere"
set mysql_connection_string "mysql://username:password@localhost/es_extended?charset=utf8mb4"
sv_maxclients 32
sv_hostname "hostnameenteredhere"
sv_scriptHookAllowed 0
sv_endpointprivacy true

stop webadmin

start mapmanager
start chat
start spawnmanager
start sessionmanager
start hardcap
start rconlog
start baseevents

start yarn

start mysql-async
start cron

start es_extended`

### Database is connecting correctly according to console:

`Creating script environments for es_extended
[esx] checking manifest
[esx] no changes required in fxmanifest.lua
Started resource es_extended
Stopping resource sessionmanager
Creating script environments for sessionmanager
Started resource sessionmanager
Authenticating server license key...
Server license key authentication succeeded. Welcome!
[mysql-async] [SUCCESS] Database server connection established.
Sending heartbeat to https://servers-ingress-live.fivem.net/ingress
[esx/core/account] start`

**Comment by DylanProd** [comment]
Hi, 

I have the same issue and i'm also on Ubuntu 18.04

**Comment by izio38** [comment]
The version of MariaDB you're using is too old. 

Please, follo the official documentation in-order-to install the latest MariaDB version. https://downloads.mariadb.org/mariadb/repositories/#distro=Ubuntu&distro_release=bionic--ubuntu_bionic&mirror=jaleco&version=10.5

Here is the version 10.5 for Ubuntu 18.04
