### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by NitroX28** [esx-framework/es_extended#852]
Ok so humm when i launch my local server, i try to connect , i can see the chat opening a few seconds to show i am connected , i can see the HUD and i heard the game  but i'm stuck on the Loadscreen , even if set it to false but if i move i can hear my footsteps so i don't know what i can do

**Comment by ollemeck** [comment]
same problem

**Comment by misua** [comment]
i am stuck at esx logo and loading with fiveM client, there is no error at the server, so unsure what i can do moving forward. anyone please help?

**Comment by xd-vape** [comment]
i am stuck too in the Loading screen

**Comment by mikemireles** [comment]
> i am stuck at esx logo and loading with fiveM client, there is no error at the server, so unsure what i can do moving forward. anyone please help?

did you fix the problem?

**Comment by mikemireles** [comment]
> > i am stuck at esx logo and loading with fiveM client, there is no error at the server, so unsure what i can do moving forward. anyone please help?
> 
> did you fix the problem?

disabling loadscreen in fxmanifest.lua works for me!

**Comment by izio38** [comment]
Are you using the `develop` branch?
