### ISSUE TITLE
Global 'ESX'

### ISSUE THREAD

**Issue by Deqwer** [esx-framework/es_extended#854]
When installing stock ESX modules have a lot of errors. 

![cmd_DweJhyGd0g](https://user-images.githubusercontent.com/29331380/85791280-3c8bc300-b73a-11ea-97df-ef72f2b4faa3.png)

![cmd_0VBWmEsSGp](https://user-images.githubusercontent.com/29331380/85791322-4c0b0c00-b73a-11ea-9ae6-7d3490d00abd.png)

**Comment by mikemireles** [comment]
> When installing stock ESX modules have a lot of errors.
> 
> ![cmd_DweJhyGd0g](https://user-images.githubusercontent.com/29331380/85791280-3c8bc300-b73a-11ea-97df-ef72f2b4faa3.png)
> 
> ![cmd_0VBWmEsSGp](https://user-images.githubusercontent.com/29331380/85791322-4c0b0c00-b73a-11ea-9ae6-7d3490d00abd.png)

did you solve this? I'm with the same problem

**Comment by Deqwer** [comment]
No! Its a problem with ESX 2, not optimized addons for new code! I dont
want to repair his code. Waiting for new versions

пн, 29 июня 2020 г. в 00:59, mikemireles <notifications@github.com>:

**Comment by evanpurl** [comment]
Having the same issue here. Hopefully it'll get fixed soon!

**Comment by HumanTree92** [comment]
Just as a heads up ESX V2 doesn't use esx_ resources. If you want to use esx_ resources try using ESX V1 Final or EXM. However once ESX V2 is finished i am pretty sure most Devs will support it.

**Comment by Dislaik** [comment]
RTFM
