### ISSUE TITLE
Server callback "esx_ventaiomenu:getCharData" does not exist.

### ISSUE THREAD

**Issue by GermanGaming** [esx-framework/es_extended#855]
## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [X ] I'm using the latest version.
- [ X] The issue has occured more than once.
- [ X] I have followed the readme and my setup is correct.
- [ X] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [X ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

It says that in the console? But I have no idea why.

[es_extended] [WARNING] Server callback "esx_ventaiomenu:getCharData" does not exist. Make sure that the server sided file really is loading, an error in that file might cause it to not load.

**Comment by izio38** [comment]
Hi, we are not providing support for V1 of Es_extended. Please go to the forum.
