### ISSUE TITLE
mysql database actions are displayed on my FXServer console

### ISSUE THREAD

**Issue by DirtyGaming** [esx-framework/es_extended#858]
## Issue Checklist

- [X] I'm using the latest version.
- [X] The issue has occured more than once.
- [X] I have followed the readme and my setup is correct.
- [X] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

__*null*__

## Current Result

__*I'm starting to see mysql logs on my console how do I disable that?*__

## How to reproduce the problem

 __*I don't know - I can't remember quiet for sure*__

## Screenshot
![image](https://user-images.githubusercontent.com/29959456/86213188-3e59ea00-bb71-11ea-9ee5-2f2debddee69.png)

**Comment by zerobit-blrp** [comment]
Use txAdmin Settings via the web panel to enable quiet mode.

**Comment by DirtyGaming** [comment]
well I'm not using txAdmin and I would like to know how to enable Quiet mode on my console without using txAdmin

**Comment by yagizher** [comment]
Its just a slow query issue and not about es_extended. Its about mysql-async, go to the documentation of mysql-async and make mysql-async save slow query isseus into a file instead of cmd.

**Comment by DirtyGaming** [comment]
Do I need to make changes to my mysql-async.js file?
![image](https://user-images.githubusercontent.com/29959456/86964009-52977b80-c15d-11ea-8921-af8e079e77f5.png)

**Comment by yagizher** [comment]
set mysql_slow_query_warning 300 # you can change the 300 to your liking.

**Comment by DirtyGaming** [comment]
Alright. I got you
So I need to add this on my server.cfg right after the mysql connection string and it will work right?

**Comment by yagizher** [comment]
Yep.
