### ISSUE TITLE
attempt to index a nil value 

### ISSUE THREAD

**Issue by Gustav987** [esx-framework/es_extended#860]
Hello i did download the new version of es extended and it might broke the esx society script
![download](https://user-images.githubusercontent.com/67919136/86622616-78d3e480-bfc0-11ea-9da9-9f1375d00fe4.png)
what can i do about it ? thanks for the help :)

**Comment by izio38** [comment]
Hi, we are not providing support for V1 of Es_extended. Please go to the forum.
