### ISSUE TITLE
Save MYSQL

### ISSUE THREAD

**Issue by surajraj12** [esx-framework/es_extended#863]
Hi,
Sorry to bother you with this but I was wondering if we could update the cash and bank from accounts as well because I was using PowerBi to monitor the circulation of money using those values and now I have an issue pulling the cash and money because it's in JSON data. Thanks for looking at this comment and sorry I had to put it in issues.

**Comment by izio38** [comment]
Hi, we are not providing support for V1 of Es_extended. Please go to the forum.
