### ISSUE TITLE
Huge issue after CEF update with the way wrapper.js/NUI calls are handled

### ISSUE THREAD

**Issue by benzon** [esx-framework/es_extended#864]
This is a problem accross all versions the way nui chunking is done dos not work with the new CEF, this has to be redone azap, it creates a ton of issues, with resources in general.

**Comment by izio38** [comment]
Next time you open an issue, please, provide more informations about what's not working and eventually what are the changes that have been made from the Fivem side.

We'll look into it.

**Comment by benzon** [comment]
@izio38 there is no need to wright a story about this, the way chunking is used in esx is messed up, and the packages are not recived in order like esx expect them to dog.

There for it breaks, with the newest CEF.

**Comment by z00t** [comment]
@benzon All he asked you for was details. Provide screenshots or more information on specifically where the breaks are and how it's "affecting resources in general".

**Comment by izio38** [comment]
If we're really talking about the v2. I think UI are just fine.

**Comment by benzon** [comment]
v2 uses chunking to so no it's not fine it will throw a soupe of errors in console when going true menus.

**Comment by izio38** [comment]
@benzon I'm using V2 right now, and it seems fine for now.

**Comment by ArkSeyonet** [comment]
This seems to be a valid issue that is occuring randomly at the moment.

@benzon Since you seem to know what this issue is well, while this issue will be looked into, would you like to provide any further information towards how you would see this issue fixed? 

We welcome you to post here with information that you know towards how to fix this issue to speed up the process, since many of the team are on other tasks as well.

**Comment by benzon** [comment]
This is a fix shared in the FiveM Discord, it's working but i doubt it's the best fix possible.

```
(() => {

    let ESXWrapper = {};
    ESXWrapper.messageId = 0;

    window.SendMessage = function (namespace, type, msg) {

        ESXWrapper.messageId = (ESXWrapper.messageId < 65535) ? ESXWrapper.messageId + 1 : 0;

        const data = {
            __type: type,
            id: ESXWrapper.messageId,
            chunk: JSON.stringify(msg),
            end: true
        }

        $.post('http://' + namespace + '/__chunk', JSON.stringify(data));
    }

})()

```

**Comment by izio38** [comment]
We'll look into it, thanks you.

**Comment by izio38** [comment]
We have been mislead in this bug. The NUI wrapper isn't the wrong part. In fact esx v2 wrapper is working (chuncking) like a charm.
