### ISSUE TITLE
Inventory module error

### ISSUE THREAD

**Issue by CalipoPA** [esx-framework/es_extended#865]
# Template

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version.
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [/] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

__*Example text*__

**Create character without errors**

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

**Running the server seems to be going perfectly but once I connect error creating character on F8 client side**

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. I use MariaDB to create the "es_extended" database
2. I run the server
3. I go in and create the character apparently an error with the inventory module when i press F2

## Errors

> Screenshot or direct copy and paste of the error from the console window.

https://imgur.com/3U37qbi

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`example code block for error context`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

Thanks for help

**Comment by Dislaik** [comment]
ESX 2 is still in development, for now, keep using the legacy version
