### ISSUE TITLE
multiple issues 

### ISSUE THREAD

**Issue by dmcpartland** [esx-framework/es_extended#868]
[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "INSERT INTO users (accounts, identifier) VALUES ('{\"bank\":50000,\"black_money\":0,\"money\":0}', 'b32cc5185c04032c7581caeda1a3ac69839bb15f')": ER_BAD_FIELD_ERROR: Unknown column 'accounts' in 'field list'
[esx] [player] loading L0RDxHarambe (1|b32cc5185c04032c7581caeda1a3ac69839bb15f)
SCRIPT ERROR: es_extended:modules/__core__/player/server/events.lua:46: attempt to index a nil value (upvalue 'row')
> task (es_extended:modules/__core__/player/server/events.lua:46)
> processQueue (@async/async.lua:67)
> parallelLimit (@async/async.lua:86)
> ref (es_extended:modules/__core__/player/server/module.lua:180)
>  (@mysql-async/mysql-async.js:14959)
SCRIPT ERROR: @esx_status/server/main.lua:66: attempt to index a nil value (global 'ESX')
SCRIPT ERROR: @esx_status/server/main.lua:66: attempt to index a nil value (global 'ESX')
SCRIPT ERROR: @esx_status/server/main.lua:66: attempt to index a nil value (global 'ESX')
SCRIPT ERROR: @esx_status/server/main.lua:66: attempt to index a nil value (global 'ESX')

**Comment by izio38** [comment]
Are you using the develop branch ?

**Comment by Dislaik** [comment]
All ESX v1 scripts are obsoleted for ESX v2
