### ISSUE TITLE
error es_extended:modules/__core__/input/module.lua:473

### ISSUE THREAD

**Issue by shentiand** [esx-framework/es_extended#870]
it is giving me this error on the F8 I only have the es_extended installed

![image](https://user-images.githubusercontent.com/68393063/87700304-82054400-c76c-11ea-878e-33b218be4a34.png)

**Comment by izio38** [comment]
Hi @shentiand what branch are you using ?

**Comment by shentiand** [comment]
Hi izio38, I am using the new version of es_extended 2.0

I am doing from scratch the whole server.

**Comment by Dislaik** [comment]
@shentiand I recommend to you continue to use the legacy version, unless you are sure what you are doing, since ESX v2 it is not a playable version yet.

**Comment by shentiand** [comment]
Hi Dislaik, thank you very much for your recommendation, the bad thing about the legacy version is that they removed the support.

**Comment by izio38** [comment]
We're not providing official support, that's right.

If you need support, wait for a stable v2 version.
