### ISSUE TITLE
Error with the item weight

### ISSUE THREAD

**Issue by Alexcorox** [esx-framework/es_extended#873]
Hi
When I try to buy something form a shop or the pharmacy of the hospital
Show this error es_extended/server/classes/player.lua:229:attempt to perform arithmetric on a nil value (local 'itemWeight')
Thanks for the help and your time
![131231](https://user-images.githubusercontent.com/68440479/87817447-3be1da80-c869-11ea-8146-cfd7ebb3856f.PNG)

**Comment by izio38** [comment]
Not a conception error actually. You just forget to change the `weight` value on the database side.

**Comment by axial47** [comment]
I changed the weight in my sql but I still got the same error...
