### ISSUE TITLE
SCRIPT ERROR: citizen:/scripting/lua/MessagePack.lua:862: extra bytes

### ISSUE THREAD

**Issue by Macgeo23** [esx-framework/es_extended#879]
- [ ] I'm using the latest version.
- [X] The issue has occured more than once.
- [X] I have followed the readme and my setup is correct.
- [X] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [X] I'm certain this is an issue with es_extended and not my personal module / script.

__*Hi , i have the problem when i'm connect to my server, my player not loading anymore, the menu won't open,.... it's appear sometime and différent player
This error appear in the console : *__

## Errors

![image](https://user-images.githubusercontent.com/53795760/87875010-85980580-c9ce-11ea-8d43-7cf95af83e26.png)

`example code block for error`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?
MessagePack : 
![image](https://user-images.githubusercontent.com/53795760/87875199-d9efb500-c9cf-11ea-808f-c1cc97c9eca9.png)
es_extended/server/function : 
![image](https://user-images.githubusercontent.com/53795760/87875217-0c99ad80-c9d0-11ea-9891-7ab776352e5a.png)
es_extended/server/common : 
![image](https://user-images.githubusercontent.com/53795760/87875230-220ed780-c9d0-11ea-93de-b5cc44a75be5.png)

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

`no idea`

**Comment by Dislaik** [comment]
Remove latest resources from your `server.cfg`, maybe can help

**Comment by Macgeo23** [comment]
This is my last resources : 
![image](https://user-images.githubusercontent.com/53795760/87882407-16d3a000-ca00-11ea-86ba-4a2e05880421.png)
 but this part it's the menu for the game x) And they say to start a the end in the server.cfg

**Comment by izio38** [comment]
This is not an issue with the `esx framework` but rather a resource using the framework. Try to find the one that causes the issue by disabling them one by one.

If you need further help, please use the resource original repository.
