### ISSUE TITLE
Failed to Load Script @es_extended/client/wrapper.lua

### ISSUE THREAD

**Issue by Kyronomix** [esx-framework/es_extended#881]
## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [X] I'm using the latest version.
- [X] The issue has occured more than once.
- [X] I have followed the readme and my setup is correct.
- [X] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [X] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

__*The loading screen should go away and the game should load my player in at the last location.*__

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

__*The screen remains on the loading screen for hours, with that error occuring.  I hear the feet drop to the ground and the sounds I should hear in the background like wind or cars but that is it.  The Eco/unemployed appears on the top right as well.*__

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. __*Removed and recloned the es_extended from github*__

## Errors

> Screenshot or direct copy and paste of the error from the console window.

[https://imgur.com/zkFXEBA](url)

Just looking for anything I can do to potentially fix this error.

**Comment by Kyronomix** [comment]
After removing essentialmode, I know, dumb to even keep it, forgot it was removed in es_extended 2.0, I got this error.

[CfxCrashDump_2020_07_20_22_15_57.zip](https://github.com/esx-framework/es_extended/files/4950274/CfxCrashDump_2020_07_20_22_15_57.zip)

**Comment by Dislaik** [comment]
https://forum.esx-framework.org/t/in-depth-esx-server-creation/812/9 and use legacy version, unless you are sure what you are doing

**Comment by izio38** [comment]
@Kyronomix If you need any further help, feel free to open a new issue.
