### ISSUE TITLE
es_extended bug start

### ISSUE THREAD

**Issue by Pikbros** [esx-framework/es_extended#887]
## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x ] I'm using the latest version.
- [x ] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [ x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

Hello i have this error and i dont know what is it due to  can you help me please
I hav database and table in sql.
![unknown](https://user-images.githubusercontent.com/36166090/88467545-70dcd580-ced8-11ea-9b50-0981ef56e2e3.png)

**Comment by Dislaik** [comment]
`Could not find dependency mysql-async for resource es_extended`
https://github.com/brouznouf/fivem-mysql-async
