### ISSUE TITLE
The link in the about section still redirects to the old docs

### ISSUE THREAD

**Issue by niekschoemaker** [esx-framework/es_extended#899]
## Issue Checklist

- [ ] I'm using the latest version (develop branch).
- [ ] The issue has occured more than once.
- [ ] I have followed the readme and my setup is correct.
- [ ] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

The link should redirect to https://esx-framework.github.io/es_extended/ instead of https://esx-org.github.io/

**_Example text_**

## Current Result

The link currently redirects to the docs in the old repo, https://esx-org.github.io/

**_Example Text_**

## How to reproduce the problem

Simply click the link in the about section

### Possible Solution

Should probably just be updated in the about section

**Comment by izio38** [comment]
What `about` section are you talking about. Thanks for reporting.

**Comment by niekschoemaker** [comment]
The one in the repo itself, so the one on the homepage of the repo: https://github.com/esx-framework/es_extended

**Comment by BrakingESX247** [comment]
It is supposed to be that way.
