### ISSUE TITLE
es_extended Final version don't use steam identifier

### ISSUE THREAD

**Issue by daroczi** [esx-framework/es_extended#900]
### I upgraded es_extended 1.0 to the final version of es_extended 1, but it doesn't work with my old systems, whic was to be expected. I nedd the essentials mod, so all I need to do is store and use the steam ID es_extended in the identifier column at the database.

_I have reworked a few lines in server/main.lua so I save SteamID nicely in the identifier column, BUT most people will get error messages in the console when they connect to the server._

![image](https://user-images.githubusercontent.com/44137084/88955623-75203e80-d29c-11ea-8756-e8206ff6da53.png)
![image](https://user-images.githubusercontent.com/44137084/88955267-fb885080-d29b-11ea-8827-0c4e5fae25d3.png)

- [ x ] The issue has occured more than once.
- [ x ] I have followed the readme and my setup is correct.
- [ x ] I have searched the ESX forum and Github issues for solution before submitting my issue.

**#####################ERRORS#####################**
![image](https://user-images.githubusercontent.com/44137084/88955716-954ffd80-d29c-11ea-939b-dcc74f2e0f3b.png)
![image](https://user-images.githubusercontent.com/44137084/88955740-9f71fc00-d29c-11ea-9a9d-ca24038005bb.png)
![image](https://user-images.githubusercontent.com/44137084/88955809-bb759d80-d29c-11ea-9c0f-e5dff32fc78c.png)
**#####################ERRORS END #####################**

**So i would need the character identification to work with steam ID (like old es_extended) , save the steam name agains as it used to the license and make the server work fine.**

Thank you for your help 🥇

**Comment by izio38** [comment]
Please, can you tell us the exact version of the framework. Thanks for reporting.

**Comment by daroczi** [comment]
> Please, can you tell us the exact version of the framework. Thanks for reporting.

fx_version 'adamant'

**Comment by izio38** [comment]
I meant the Esx version, you said : `es_extended 1.0 to the final version of es_extended 1`, so I think you're using the latest version in the `final` branch, right?

**Comment by daroczi** [comment]
> I meant the Esx version, you said : `es_extended 1.0 to the final version of es_extended 1`, so I think you're using the latest version in the `final` branch, right?

Yes.

**Comment by BrakingESX247** [comment]
You simply cannot use essentialmode with the database structure of es_extended v1 final. Consider getting ExtendedMode or a earlier version of es_extended. Even if you find a way of using essentialmode with v1 final, it is not recommended.

**Comment by mafioso1337** [comment]
hello could you send me your es_extended ? I really need one with weight system and steam id system , please only you can save me

**Comment by mafioso1337** [comment]
I need this es_extended with system identifier steam id can help me ? Please
