### ISSUE TITLE
How do you get the shared object?

### ISSUE THREAD

**Issue by iWanheda** [esx-framework/es_extended#901]
I've gone through the docs, couldn't find it

**Comment by izio38** [comment]
That's very true, thanks for reporting.

**Comment by izio38** [comment]
Some of the scripters do it like this : 

```lua
-- store a global variable ESX
ESX = nil

Citizen.CreateThread(function()
  -- while it's not resolved
  while ESX == nil do
    -- get it if instanciated yet
    TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
    Citizen.Wait(0)
  end
end)
```

**Comment by iWanheda** [comment]
```
ESX             = nil

Citizen.CreateThread( function( )
	while ESX = nil do
		TriggerEvent( 'esx:getSharedObject', function( obj ) ESX = obj end )
		Citizen.Wait( 0 )
	end
end )
```

Error:
[https://b.catgirlsare.sexy/tyhbtZqr.png](img)

Line 55:
`ESX.RegisterServerCallback('esx_shops:requestDBItems', function(source, cb)`

**Comment by iWanheda** [comment]
Have I gotten a big ghost?

**Comment by BrakingESX247** [comment]
The error is not releated to ESX itself. The provided example is the to-go way of retrieving the ESX library, both client and server side.

**Comment by Darkkaiserl** [comment]
Same here, in es_extended ESX 2 this code doesn't work.

Example: 
```lua
ESX = nil
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
``` 
(this is in esx_skin)

result this error: 
![image](https://user-images.githubusercontent.com/30737924/89741310-86203b00-da66-11ea-9333-8e5036fed17a.png)


How i get ESX obj?.

**Comment by BrakingESX247** [comment]
You don't get shared object in ESX 2. Please read the documentation and do not use V2 if you don't know what it is and don't know how to deal with it.

**Comment by Darkkaiserl** [comment]
Thanks so much...
