### ISSUE TITLE
[ESX 1.2] GetNeworkObject

### ISSUE THREAD

**Issue by DmACKGL** [esx-framework/es_extended#910]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ ] I'm using the latest version (develop branch).
- [x] The issue has occurred more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for the solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module/script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behavior should occur.

Know where this error happens and how to fix it

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

![image](https://user-images.githubusercontent.com/10565361/89120873-a5780080-d487-11ea-920c-eac83b3f77e0.png)

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. /car police (Or any vehicle)
2. /dv

## Errors

> Screenshot or direct copy and paste of the error from the console window.

```gta-core-five: GetNetworkObject: no object by ID <Number>```
### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`example code block for error context`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

None.

**Comment by Dislaik** [comment]
Probably you have much entities in your server (cars, npc, etc.)
