### ISSUE TITLE
EssentialMode Doesn't Load on the "top" of ESX

### ISSUE THREAD

**Issue by kalinzange** [esx-framework/es_extended#911]
## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [X] I'm using the latest version (develop branch).
- [X] The issue has occurred more than once.
- [X] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

I have setup ESX and EssentialMode into my server. In essentialmode if you go to Server > util.lua and change the valus for  startingCash and startingBank while starting up the server again and check the money isn't updated.

I know I can go to es_extended > config > default > config.lua and change from there, but I wonder if essentialmode isn't loaded on the "top" of ESX

**Comment by Dislaik** [comment]
Essentialmode don't work with ESX 2 (why you try using two framworks?)
