### ISSUE TITLE
User doesn't load from DB

### ISSUE THREAD

**Issue by EasyCompZLD** [esx-framework/es_extended#913]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ x] I'm using the latest version (develop branch).
- [ x] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [ x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

continuing from https://github.com/esx-framework/es_extended/issues/912 
Users should load from database right now it writes to the db but it doesn't read

**_Example text_**

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).
i stay a tourist but i see the table data in the db 
https://ibb.co/rs9WLtt

**_Example Text_**

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. tried to update es_ext...  https://github.com/esx-framework/es_extended/issues/912 
2. Downgraded es ext
3. sigh moment...

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`example code block for error`

### Code Block referenced by the error
none are visible 

> If the code references a specific line of code within a file, what line is it?

`example code block for error context`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

`example code block for solution`

**Comment by Dislaik** [comment]
Maybe you didn't a correct installation, try following this https://wiki.esx-framework.org/es_extended2/installation/
