### ISSUE TITLE
error with es_extended 

### ISSUE THREAD

**Issue by VladiSMV** [esx-framework/es_extended#915]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

**_Example text_**

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

**_the es_extended is not starting or somethig doesent works it is just not working 
no error is showing up_**

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1.**_I tried updating all of the requierd_**
2. **_I tried looking in the code_**
3. **_And now i am reporting the error :)_**

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`example code block for error`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`example code block for error context`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

`example code block for solution`

**Comment by Dislaik** [comment]
more info please

**Comment by Dislaik** [comment]
Maybe you didn't a correct installation, try following this https://wiki.esx-framework.org/es_extended2/installation/
