### ISSUE TITLE
Everyone can use admin commands

### ISSUE THREAD

**Issue by LeoLight868** [esx-framework/es_extended#925]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

**I should not be able to use any commands**

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

**I should not be able to use any commands **

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. **I downloaded a fresh download from FiveM to make a server**
2. **I downloaded this version of es_extended v1-final and add required file like asyn etc. set the config up**
3. **run the server. join and i am able to use admin commands like /giveitem etc an my group in the database is set to user**

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`below is basically my cfg.

ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard

add_principal group.admin group.user
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow

start mysql-async
start es_extended

start esx_menu_default
start esx_menu_list
start esx_menu_dialog`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`example code block for error context`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

`I have another server set up with all the other resources like properties, stores, job etc and this still happened. until i removed essentailmode from that server and it worked as it shud. but then after restart, erveryone cud use admin commands. So i created a brand new server with only the baisc files. no jobs, no essentialmode. and i can still use admin commands
![ex](https://user-images.githubusercontent.com/58056944/89972562-207dab80-dc2c-11ea-9226-b72ba6a5fb5b.PNG)
 `

**Comment by Dislaik** [comment]
Probably you became an admin in server.cfg group.admin

**Comment by LeoLight868** [comment]
HOW? i didnt put my steam id or anything like that

**Comment by Grogyas** [comment]
Same here
