### ISSUE TITLE
Hi there,  We are experiencing a issue when we try to recruit " in game " 

### ISSUE THREAD

**Issue by KrambaZeta** [esx-framework/es_extended#929]
## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [ ] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

Hi there, we are having issue recruiting " in game " as an error occur 

The server is running on esx v1 final

[es_extended] [WARNING] Ignoring invalid .setjob( ) usage for cb5c90410fbe835a85f718fd937b9ee1595aa4c 

Have a good day

Thanks,

KrambaZeta

**Comment by TheoBIET** [comment]
hello, have u got this problem with the last release ?

**Comment by KrambaZeta** [comment]
Hey there,

Yes its a real struggle. We switched on a core base wich is working with
esx without using it directly its more simple and more faster in game.

Hope you can solve this issue as we havn't even now find it :/

Have a good day

Cordially,

Aurélien.

**Comment by itschip** [comment]
Does not seem like an serious issue, nor will we fix it. Have a nice day, chip.
