### ISSUE TITLE
Drawing showHelpNotification & howFloatingHelpNotification

### ISSUE THREAD

**Issue by st860923** [esx-framework/es_extended#931]
if drawing showHelpNotification  and howFloatingHelpNotification in same time,
howFloatingHelpNotification position will going left top  ( showHelpNotification  position ) .
how can i resloved it

**Comment by Darkkaiserl** [comment]
Are you sure using "develop" version?

I used this, and it's fine.
``` lua
utils.ui.showNotification("Test")
utils.ui.howFloatingHelpNotification("Test", GetEntityCoords(PlayerPedId()), 10000)
```

**Comment by st860923** [comment]
I have tried many versions, 
in some scenarios, when Drawing showNotification then -> show howFloatingHelpNotification
howFloatingHelpNotification will flashing on left top screen, ( position issue ), and showNotification got replaced.
