### ISSUE TITLE
Random spawn fresh setup

### ISSUE THREAD

**Issue by zemmsoares** [esx-framework/es_extended#932]
Players get random spawn using old es_extended,
https://github.com/ESX-Org/es_extended/tree/v1-final

Also tried the esx community fork which spawn appears to be working but ped creation pop up everytime i spawn. Disabled steamID on esx_identity config which removes the menu, but /skin still shows.

**Comment by Moonlgiht111** [comment]
Did you fix it?

**Comment by zemmsoares** [comment]
yes @Moonlgiht111 , i believe it has something to do with `mapmanager` and `spawnmanager` comment those on server.cfg

**Comment by BattleStar247** [comment]
I have same issue but if I close spawnmanager my whole esx breaks. I know it's been a year but I can't find any solution
