### ISSUE TITLE
Issue with this version of es_extended

### ISSUE THREAD

**Issue by SkyRP25** [esx-framework/es_extended#934]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.
![image](https://user-images.githubusercontent.com/69591248/90881643-7677ef00-e3a2-11ea-841c-194ca40ce962.png)
 I have a lot of issues with difesrents scripts loading in the lastest version of es_extended, I v1 it work well. but with this version it doesn't, this photo shows some of the errors, but I hvae plenty more, but they are the sema "Attempt to index a nil values ("ESX")"

Pls I need help

**Comment by ArkSeyonet** [comment]
Do not download from master branch. Use the releases to get esx1 files. Master Branch Download is now part of ESX2.
