### ISSUE TITLE
es_extended conncet

### ISSUE THREAD

**Issue by Patres1839** [esx-framework/es_extended#936]
Hello, I have a new es_extended, I uploaded it to the database and I can't connect to the server. This lists me as a help. 
![2020-08-23 (2)](https://user-images.githubusercontent.com/70112939/90988786-d08cd600-e595-11ea-992a-fa2f687dae60.png)
![2020-08-23 (9)](https://user-images.githubusercontent.com/70112939/90988792-db476b00-e595-11ea-9f8d-e2c3710055b8.png)
![2020-08-23 (10)](https://user-images.githubusercontent.com/70112939/90988795-e4383c80-e595-11ea-9e5b-5819d4387637.png)
@BrakingESX247

**Comment by Dislaik** [comment]
RTFM https://wiki.esx-framework.org/es_extended2/installation/
