### ISSUE TITLE
es_extended: TriggerServerCallback => [esx_society:getSocietyMoney] does not exist

### ISSUE THREAD

**Issue by DooubleTap** [esx-framework/es_extended#937]
- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

I cannot open the boss action menu, and i get spammed wit this error in the console. 
es_extended: TriggerServerCallback => [esx_society:getSocietyMoney] does not exist

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

the boss menus will not open. 

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

i installed the latest es_extended esx_society and esx_policejob and i get this error. 

## Errors

> Screenshot or direct copy and paste of the error from the console window.

[https://i.imgur.com/dZLRRSf.png](https://i.imgur.com/dZLRRSf.png)

**Comment by SkyRP25** [comment]
Same here

**Comment by ArkSeyonet** [comment]
Do not download from master branch, as none of those scripts will work. Use releases.
