### ISSUE TITLE
How to update from es_extended v1 to es_extended V2

### ISSUE THREAD

**Issue by Goontje** [esx-framework/es_extended#939]
I would realy like to know how to update on a server that is currently running on es_extended v1 to the newest version.

If i just update the files and update the database will that fix everything ?
I Think the whole server will be screwed after.

Please help ?

**Comment by Bastiti** [comment]
Hi, firstly do you have some esx_ scripts ?

**Comment by Goontje** [comment]
@Bastiti, Thank you for your response!
Yes I do have plenty of esx_scripts running.

**Comment by Bastiti** [comment]
Ok. So, don't update to v2. This will make incompatible all your esx_ scripts. As the v2 works with module and doesn't offer compatibility for something else to keep stability and performance.

**Comment by dkdknight** [comment]
il doit bien y avoir une solution

**Comment by bilbodog** [comment]
Well, this is really **not** good...

ESX should seriously consider making some kinda integration, so people have a possibility to not use the module function only.
ESX is asking everyone to basically start over.

**Comment by ArkSeyonet** [comment]
We aren't asking anyone to do anything. That is why we left esx1 files available for download.

We at ESX Team are done with esx1, and want to move onto making a better framework. You can accept that, and move on with us, or you can stay on esx1. It's your decision.
