### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Iamcs1998** [esx-framework/es_extended#940]
Hi
First of all, Thank you so much for your fantastic work
I just have a question : 
Is it completely ready to use?
or still, need to develop ?

**Comment by Combat116** [comment]
I have the same problem.

**Comment by Iamcs1998** [comment]
It seems is ready but people say it's not I'm so confused

**Comment by ArkSeyonet** [comment]
It is not ready. It will not be ready for quite a while, a framework is not an easy task.
