### ISSUE TITLE
My es_extended takes to much time to load

### ISSUE THREAD

**Issue by MrAlmagro** [esx-framework/es_extended#942]
My issue is that the es_extended takes to much time to fully load
This makes the scripts that go before not to load correctly.
Look at the screencaps[](url)
![Captura de pantalla (440)](https://user-images.githubusercontent.com/60575446/91667355-49df7800-eb04-11ea-970a-493a5271dedf.png)
![Captura de pantalla (439)](https://user-images.githubusercontent.com/60575446/91667359-4ea42c00-eb04-11ea-9354-b277322ae0b4.png)

**Comment by Explooosion-code** [comment]
Scripts that you are showing are using ESX version 1 but current version of esx is ESX 2 wich is not compatible with v1 scripts...
