### ISSUE TITLE
Onesync

### ISSUE THREAD

**Issue by epicgameruk** [esx-framework/es_extended#943]
How can I get esx to work with onesync

**Comment by Bencey** [comment]
What do you mean? The script already works with onesync

**Comment by epicgameruk** [comment]
Yea but certain scripts wernt and stopped me from doing certain things, u have installed instance-onesync and fixed everything, the only issue I'm having is my players characters aren't loading and I am unsure it could be either, esx_skin, skin changer or kashacters

**Comment by johnsoul777** [comment]
> Sí, pero ciertos scripts fallaron y me impidieron hacer ciertas cosas, instaló instance-onesync y solucionó todo, el único problema que tengo es que los personajes de mis jugadores no se cargan y no estoy seguro de que pueda ser, esx_skin, skin cambiador o kashacters

Prueba quitando el spawnmanager de tu config.cfg, a mi me funciono.
