### ISSUE TITLE
Error pls do not close

### ISSUE THREAD

**Issue by VladiSMV** [esx-framework/es_extended#947]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] I have followed the readme and my setup is correct.
- [x] The issue has occured more than once.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> to work

**_i need it to work :)_**

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

**_i bought host and the database is connected but when i enter the user doese not register and i dont know what to do_**

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. **_i tried to remake my database_**
2. **_i tried to drop and upload again_**
3. **_i tried to find the problem_**

## Errors

> Screenshot or direct copy and paste of the error from the console window.

`SCRIPT ERROR: @es_extended/server/main.lua:123: attempt to index a nil value (field '?')
ref (@es_extended/server/main.lua:123)
(@mysql-async/mysql-async.js:15543)`

### Code Block referenced by the error

> If the code references a specific line of code within a file, what line is it?

`nothing`

### Possible Solution

> If you have an idea of a potential solution or have a suggestion of how to fix the issue please write it below.

`nothing`

**Comment by VladiSMV** [comment]
DISCORD:VladiSMV#4236

**Comment by XvenDeR** [comment]
close this
