### ISSUE TITLE
Blips wont move

### ISSUE THREAD

**Issue by thunderstorm91** [esx-framework/es_extended#948]
## Bug Report

> Please use the template below and replace all example lines with your issue!

## Issue Checklist

> Please put `x` inside of the box that matches your issue.

- [x] I'm using the latest version (develop branch).
- [x] The issue has occured more than once.
- [x] I have followed the readme and my setup is correct.
- [x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ ] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result

> In a few short sentences please tell us what the expected result / correct behaviour should occur.

i can move any blips on my may eg like the police station change room

## Current Result

> In a few short sentences please tell us what is currently happening and isn't "normal" (Images are strongly recommended).

when change of cords happen the blip does not move

## How to reproduce the problem

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?

1. installed new script eg ambulance job change cords nothing changes

**Comment by tomasalves8** [comment]
You are probably changing the coordinates in the wrong place, is this occuring in every script, or one in specfic?

**Comment by ArkSeyonet** [comment]
If you are using the develop branch, then "installing new scripts" will not work the same way as in ESX1. You have to create a new ambulance job module instead of just installing ambulancejob script if you want it to work with ESX2 (the develop branch is esx2, not esx1. any script labeled as esx_***** is esx1)
