### ISSUE TITLE
How do I get started with the new es_extended

### ISSUE THREAD

**Issue by Vacsson** [esx-framework/es_extended#955]
I do not understand anything about the new es_extended. Someone make a tutorial how to get a server running with this?

I am only getting error from the sql when starting the server etc.

**Comment by Frawnefeller** [comment]
@Vacsson Hi, I understand, your problem, sorry if maybe I write wrong but I'm using google translate "I'm Italian"
this is my server.cfg

add_ace resource.essentialmode command.sets allow
add_ace resource.essentialmode command.add_principal allow
add_ace resource.essentialmode command.add_ace allow

set mysql_connection_string "user=root;database=es_extended"

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard

# Resources
start async

# ESX
ensure mysql-async
ensure cron
ensure skinchanger
start essentialmode
start esplugin_mysql
start es_admin2
start es_ui
ensure es_extended
start esx_skin
start esx_menu_default
start esx_menu_list
start esx_menu_dialog

Quite simply, the file named es_extended.sql is misspelled, so I modified it. I think just write the following on the query:
CREATE DATABASE IF NOT EXISTS `es_extended`;
USE `es_extended`;

CREATE TABLE `users` (
	`identifier` VARCHAR(40) NOT NULL,
	`accounts` LONGTEXT NULL DEFAULT NULL,
	`group` VARCHAR(50) NULL DEFAULT 'user',
	`inventory` LONGTEXT NULL DEFAULT NULL,
	`job` VARCHAR(20) NULL DEFAULT 'unemployed',
	`job_grade` INT(11) NULL DEFAULT 0,
	`loadout` LONGTEXT NULL DEFAULT NULL,
	`position` VARCHAR(53) NULL DEFAULT '{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}',

	PRIMARY KEY (`identifier`)
);

CREATE TABLE `items` (
	`name` VARCHAR(50) NOT NULL,
	`label` VARCHAR(50) NOT NULL,
	`weight` INT(11) NOT NULL DEFAULT 1,
	`rare` TINYINT(1) NOT NULL DEFAULT 0,
	`can_remove` TINYINT(1) NOT NULL DEFAULT 1,

	PRIMARY KEY (`name`)
);

CREATE TABLE `job_grades` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`job_name` VARCHAR(50) DEFAULT NULL,
	`grade` INT(11) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`label` VARCHAR(50) NOT NULL,
	`salary` INT(11) NOT NULL,
	`skin_male` LONGTEXT NOT NULL,
	`skin_female` LONGTEXT NOT NULL,

	PRIMARY KEY (`id`)
);

INSERT INTO `job_grades` VALUES (1,'unemployed',0,'unemployed','Unemployed',200,'{}','{}');

CREATE TABLE `jobs` (
	`name` VARCHAR(50) NOT NULL,
	`label` VARCHAR(50) DEFAULT NULL,

	PRIMARY KEY (`name`)
);

INSERT INTO `jobs` VALUES ('unemployed','Unemployed');

If that doesn't work, then edit the .sql file and add what I wrote earlier. The database name will need to be es_extended so whenever you put new .sql files into the database make sure you edit them and put them in the database that is assigned. If you have other types of problems send another message in this chat that I will be very happy to help you ;)
Good day

**Comment by itschip** [comment]
Lets not do that, as it does not seem like he is asking for that version.

https://esx-framework.github.io/es_extended2/installation/

Read this
