### ISSUE TITLE
ESX globals are nil in child resources

### ISSUE THREAD

**Issue by steveski** [esx-framework/es_extended#957]
I'm setting up a new server from scratch and trying to understand why esx_skin and esx_identity are failing to set the global ESX variable.
```
Error loading script server/main.lua in resource esx_identity: @esx_identity/server/main.lua:218: attempt to index a nil value (global 'ESX')
stack traceback:
        @esx_identity/server/main.lua:218: in main chunk
Failed to load script server/main.lua.
Started resource esx_identity
Creating script environments for esx_skin
Error loading script server/main.lua in resource esx_skin: @esx_skin/server/main.lua:38: attempt to index a nil value (global 'ESX')
stack traceback:
        @esx_skin/server/main.lua:38: in main chunk
Failed to load script server/main.lua.
Started resource esx_skin
```

My loaded resources are defined like this
```
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard
ensure baseevents

ensure mysql-async
ensure cron

ensure es_extended

ensure esx_menu_default
ensure esx_menu_list
ensure esx_menu_dialog

ensure skinchanger
ensure esx_skin
ensure esx_identity
```

FiveM server version is 3017. I was initially trying to use the latest release zips on our resources but realised they're years behind. All resources installed are from master branch as of 2020-10-10.

I can't see why these globals aren't being set by the TriggerEvent call at the start of the script files.
I have created a git repo of our current broken setup [here](https://github.com/steveski/esx-support)
Would greatly appreciate any advice.

**Comment by ArkSeyonet** [comment]
Do not load es_extended from master branch, as that is not part of esx1 anymore. You must download the v1-final release of es_extended.
