### ISSUE TITLE
ERR_DEADLOCK

### ISSUE THREAD

**Issue by bertusdev** [esx-framework/es_extended#958]
Hi,

I'm having issues from time to time when people buy items or store things.
The error is like this one:

[ERROR] [MySQL] [es_extended] An error happens on MySQL for query "UPDATE user_inventory SET count = 10 WHERE identifier = 'steam:11000011705f1a4' AND item = 'water'": ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction

Obviously, that transaction got lost, so the user lost whatever they've bought or stored.

How can I solve this?

**Comment by itschip** [comment]
Make sure you have no other queries that lock access more than one key at a time except for the delete statement. if you do (and I suspect you do), order their WHERE in (k1,k2,..kn) in ascending order.
