### ISSUE TITLE
Module loading on V2.0.1

### ISSUE THREAD

**Issue by jdebetaz** [esx-framework/es_extended#962]
Dear Team,

I'm trying to create a module with the current latest version (2.0.1) and it seams that my module is not loading in the game console.

I followed everything on your [documentation](https://esx-framework.github.io/es_extended2/modules/)  but nothing is working or appending.

Kind regards.

**Comment by itschip** [comment]
Did yo add it in the modules.json file?

**Comment by jdebetaz** [comment]
Yes, i added all my modules in the `modules.json`
