### ISSUE TITLE
Error loading script fxmanifest.workaround.js in resource es_extended: Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by schwim0341** [esx-framework/es_extended#965]
This is a fresh ESX install using linux 3078 arties.  There are no additional resources installed, just latest cfx-server-data and esx develop branch/required dependencies.

## Issue Checklist
> Please put `x` inside of the box that matches your issue.
- [ x] I'm using the latest version (develop branch).
- [ x] The issue has occured more than once.
- [ x] I have followed the readme and my setup is correct.
- [ x] I have searched the ESX forum and Github issues for solution before submitting my issue.
- [ x] I'm certain this is an issue with es_extended and not my personal module / script.

## Expected Result
The expected result is for the error not to show in server terminal on startup.

## Current Result
The following error occurs during fresh install startup:

. . .
Creating script environments for es_extended
Error loading script fxmanifest.workaround.js in resource es_extended: Error: Cannot find module 'glob'
Require stack:
- /path/to/fivem/esxv2/resources//[esx]/es_extended/dummy.js
stack:
[object Object],[object Object],[object Object],[object Object],[object Object]
Failed to load script fxmanifest.workaround.js.
Started resource es_extended
. . .

> What steps did you take for the issue to occur? What would we have to do for the same result to happen?
Start the server

Just thought I would post this as I couldn't find any mention of it.

**Comment by ArkSeyonet** [comment]
This issue happens because you didn't follow the instructions properly in the Documentation: https://wiki.esx-framework.org/es_extended2/installation/

**Comment by MightyBeno** [comment]
I'm having the same issue and the documentation is down.

**Comment by MightyBeno** [comment]
Ok, documentation is up but I'm still getting the issue.
