### ISSUE TITLE
random spawn

### ISSUE THREAD

**Issue by guccistre** [esx-framework/es_extended#988]
why sometimes when I enter the server there is a random spawn position, sometimes the last position, I want to make it to the last position when I logged in. help.. 
Using es extended 1 final

**Comment by vcentenop** [comment]
Hi guccistre I have the same issue. Es_extendend seems to save the last position in Database but when it loads sometimes works and sometimes not. I Think more Not xD.
I had read a lot about this but didnt find any solution. Changed resource orders....Changed type of data to LONGTEXT or JSON and... nothing...

**Comment by TheoBIET** [comment]
as-tu vérifié dans le spawn manager en ne mettant qu'une seule coordonnées de départ? et spawnez vous en Peds ?

**Comment by guccistre** [comment]
yes, sometimes in the last position, sometimes in random positions

Pada tanggal Rab, 4 Nov 2020 pukul 00.31 Théo <notifications@github.com>
menulis:

**Comment by TheoBIET** [comment]
probably an error on your db

**Comment by itschip** [comment]
cool
